### ISSUE TITLE
Migration to Temporal

### ISSUE THREAD

**Issue by HonzaTuron** [airbnb/react-dates#2194] opened 2022-04-13 13:50 UTC
Temporal finally reached [Stage 3](https://github.com/tc39/proposals#stage-3) and there's also [pretty good polyfill](https://www.npmjs.com/package/@js-temporal/polyfill) available as npm package.

I think it would be great to migrate obsolete moment library to Temporal.

**Comment by ljharb** [comment] 2022-04-13 13:52
Duplicate of #208.

Temporal shouldn’t be at stage 3 yet, really, because it’s still having normative changes. When that settles down, it’ll be time to consider it.

Additionally, that polyfill isn’t anywhere near backwards compatible enough to be sufficient.

**Closed as completed by ljharb** 2022-04-13 13:52 UTC
