### ISSUE TITLE
Cannot upgrade react to v17 or v18 due to restriction by this library

### ISSUE THREAD

**Issue by medin-n** [airbnb/react-dates#2209] opened 2022-07-08 12:13 UTC
**react-dates version**
e.g. react-dates@21.8.0
**Describe the bug**
When upgrading React to newer version v17 or v18 I get this npm error that I cannot upgrade due to this library restriction.
Can you elaborate on why this library would not work with the newer react version?

I am blocked since Microsoft AppInsignts has a restriction that I must upgrade the project to newer react

**Source code (including props configuration)**

When running `npm install`
```
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14 || ^15.5.4 || ^16.1.1" from react-dates@21.8.0
npm ERR! node_modules/react-dates
npm ERR!   react-dates@"^21.8.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

**Comment by ljharb** [comment] 2022-07-08 15:18
Yes, this is the situation right now, you must use react 16 with this library.

Duplicate of #2105. Duplicate of #2199.

**Closed as not planned by ljharb** 2022-07-08 15:18 UTC

**Comment by orangecoding** [comment] 2022-07-09 10:56
This is becoming a blocker for tons of os projects.

I do understand there are issues why a migration is hard, however tagging this as not planning is something you should definitely but in your readme, so that people are aware and do not even start integrating this lib if they want to stay up to date with react 18.

Just my 2 cents, it's ok not to take the effort, but then be transparent to everybody :)

**Comment by ljharb** [comment] 2022-07-09 15:25
@orangecoding i closed it as a duplicate. The migration is quite planned; see the linked issues.
