### ISSUE TITLE
Warnings in different components

### ISSUE THREAD

**Issue by NaumanMoazzam** [airbnb/react-dates#2172] opened 2022-01-10 20:04 UTC
**react-dates version**
e.g. react-dates@21.8.0
<img width="1435" alt="Screenshot 2022-01-10 at 12 59 34 PM" src="https://user-images.githubusercontent.com/30693949/148831520-9cf36009-185d-4ef3-8cee-e094164c7a9d.png">

This screenshot is self explanatory!

**Comment by ljharb** [comment] 2022-01-10 21:01
Duplicate of #1748.

**Closed by ljharb** 2022-01-10 21:01 UTC
