### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by Dibro89** [airbnb/react-dates#484] opened 2017-05-03 15:54 UTC
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "react-dates" "moment@(2.10-2.14||^2.15.1)&&<2.18.0" "react@>=0.14" "react-dom@>=0.14" "react-addons-shallow-compare@>=0.14"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: moment@(2.10-2.14||^2.15.1)&&<2.18.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 2.18.1, 2.18.0, 2.17.1, 2.17.0, 2.16.0, 2.15.2, 2.15.1, 2.15.0, 2.14.1, 2.14.0, 2.13.0, 2.12.0, 2.11.2, 2.11.1, 2.11.0, 2.10.6, 2.10.5, 2.10.3, 2.10.2, 2.9.0, 2.8.4, 2.8.3, 2.8.2, 2.8.1, 2.7.0, 2.6.0, 2.5.1, 2.5.0, 2.4.0, 2.3.1, 2.3.0, 2.2.1, 2.1.0, 2.0.0, 1.7.2, 1.7.1, 1.7.0, 1.6.2, 1.6.1, 1.6.0, 1.5.1, 1.5.0, 1.4.0, 1.3.0, 1.2.0, 1.1.1, 1.1.0, 1.0.1, 1.0.0
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by majapw** [comment] 2017-05-03 16:03
@ljharb Does that syntax not work in certain circumstances? It should match on 2.15.1 - 2.17.1.

Incidentally, we can probably unpeg that.

**Comment by jinalskothari** [comment] 2017-05-03 16:05
macOS Sierra 10.12.4
node --version v7.1.0
npm --version 4.4.0
zsh
Same issue.

**Comment by Dibro89** [comment] 2017-05-03 16:14
@jinalskothari you can manually install moment. The latest acceptable version is 2.17.1

**Comment by majapw** [comment] 2017-05-03 16:19
This is weird. I am unable to reproduce with either of your node/npm versions. :/

**Comment by Dibro89** [comment] 2017-05-03 16:20
@majapw I'm using git-bash for Windows. May this be the cause?

**Comment by majapw** [comment] 2017-05-03 16:23
@jinalskothari is on the same version of mac OS as I am though and running into the same issue though. I'll wait for @ljharb to chime in, since he probably has more context on the node/npm stuff that might be leading to this problem.

**Comment by jinalskothari** [comment] 2017-05-03 16:32
@majapw I am not too familiar with how npm & package.json work. Would be happy to help in reproducing the issue and documenting steps.
@Dibro89 Your suggestion was helpful, I installed the moment dep manually. 

For some reason, I had issues with `react-addons-shallow-compare` as well. Adding that manually, deleting `node_modules` and `npm install` did the job.

**Comment by ljharb** [comment] 2017-05-03 18:04
That semver syntax should work perfectly fine, but you should use https://npmjs.com/install-peerdeps on windows to install peer deps, since the command line can be funky there.

**Comment by Dibro89** [comment] 2017-05-04 05:57
@ljharb Thanks. Also as I understand the only reason why we are using this command is dependency on older moment. Why don't you update it?

**Comment by ljharb** [comment] 2017-05-04 06:02
@Dibro89 that's the only reason we're using that *specific* semver string - you'll need the command forever, because moment is a singleton, and all singletons must be peer dependencies.

**Comment by chris-pearce** [comment] 2017-05-04 06:06
I'm also getting the same issue as @Dibro89 reported at the start.

```bash
Chris-Pearces-MacBook-Pro: DesignSystemContext.DesignSystemService git:( INS-384 U:3 ?:1 ✗ ) $ (
>   export PKG=react-dates;
>   npm info "$PKG" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g; s/ *//g' | xargs npm install --save "$PKG"
> )
npm ERR! code ETARGET
npm ERR! notarget No compatible version found: moment@(2.10-2.14||^2.15.1)&&<2.18.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 2.0.0, 2.1.0, 2.2.1, 2.3.0, 2.3.1, 2.4.0, 2.5.0, 2.5.1, 2.6.0, 2.7.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0, 2.10.2, 2.10.3, 2.10.5, 2.10.6, 2.11.0, 2.11.1, 2.11.2, 2.12.0, 2.13.0, 2.14.0, 2.14.1, 2.15.0, 2.15.1, 2.15.2, 2.16.0, 2.17.0, 2.17.1, 2.18.0, 2.18.1
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chrisp/.npm/_logs/2017-05-04T05_28_59_337Z-debug.log
```

* macOS Sierra 10.12.4
* Node: `v7.9.0`
* NPM: `4.5.0`

I then manually installed:

```bash
npm install --save-dev react-dates react-addons-shallow-compare moment
```

And it added ~290kb to my Webpack bundle! I'm assuming I need to be specific with versions? However, it would be great if:

```bash
(
  export PKG=react-dates;
  npm info "$PKG" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g; s/ *//g' | xargs npm install --save "$PKG"
)
```

Worked.

**Comment by ljharb** [comment] 2017-05-04 06:14
@chris-pearce as for the size, that's because moment is large when webpack naively bundles up all of the locales. There's specific workarounds for it; you'll need to refer to the moment repo for that.

I've been able to reproduce this locally; the issue is caused by the `&&` and `<` in the output not being quoted. I'll fix it.

**Comment by ljharb** [comment] 2017-05-04 06:20
This will be released in the next patch to v11. It appears this has been an issue in all of v8, v9, v10, and v11.

**Closed** 2017-05-04 06:19 UTC

**Comment by chris-pearce** [comment] 2017-05-04 06:33
Thanks.

I'll dig around the **moment** repo about the size issue as yeah it's bigger than my whole component library bundle 😢 .

**Comment by chris-pearce** [comment] 2017-05-04 07:00
@ljharb I know you're busy mate but if you have any links to those _specific workarounds_ handy that would be great? I've started trawling through the moment repo GH Issues and haven't found anything yet, e.g.: https://github.com/moment/moment/issues/3917.

**Comment by ljharb** [comment] 2017-05-04 07:21
I'm afraid I've never ran into it; https://github.com/moment/moment/issues/3674#issuecomment-271207891 implies that it might be a webpack bug instead of something moment itself deals with.

**Comment by chris-pearce** [comment] 2017-05-04 08:01
@ljharb cheers. I managed to shave off ~120kb, still massive. Anyway thanks for your help and speedy fix to the original issue.
