### ISSUE TITLE
[Feature Request] Preset date ranges

### ISSUE THREAD

**Issue by ianks** [airbnb/react-dates#29] opened 2016-08-19 18:12 UTC
One thing that is necessary for an app that I am building is preset date ranges. For what I am doing, it is a bad UX to force users to pick specific dates always; oftentimes they want just the data from the last week/month/etc. I understand that for Airbnb this is not a valid use case, but for many other styles of it is. A good mockup for how this might look is from bootstrap-daterange-picker:

![calendar-with-presets](https://camo.githubusercontent.com/1083660a91a3d95a2dd4e8e5e74dfc9703fcdadd/687474703a2f2f692e696d6775722e636f6d2f4c62414d6633442e706e67)

Would the maintainers be open to accepting a PR with the feature if it was not part of the default configuration?

**Comment by mikesparr** [comment] 2017-01-16 21:54
@ianks you can build your own either as dropdown next to picker, links, or get fancy and add to div.

Simple implementation re-using the change callback

~~~
<a href="#" onClick={() => this.onDatesChange({startDate: moment.utc().subtract(1, 'year'), endDate: moment.utc()})}>Year</a> | &nbsp;
<a href="#" onClick={() => this.onDatesChange({startDate: moment.utc().subtract(3, 'months'), endDate: moment.utc()})}>Qtr</a> | &nbsp;
<a href="#" onClick={() => this.onDatesChange({startDate: moment.utc().subtract(1, 'month'), endDate: moment.utc()})}>Mo</a> | &nbsp;
<a href="#" onClick={() => this.onDatesChange({startDate: moment.utc().subtract(1, 'week'), endDate: moment.utc()})}>Week</a> | &nbsp;
<a href="#" onClick={() => this.onDatesChange({startDate: moment.utc().subtract(1, 'day'), endDate: moment.utc()})}>Day</a> 
~~~

<img width="1201" alt="screen shot 2017-01-16 at 2 37 02 pm" src="https://cloud.githubusercontent.com/assets/5553105/21999865/70f3e25a-dbf9-11e6-8456-3544def7cbb3.png">

**Comment by sharq1** [comment] 2017-06-30 11:33
Check out our extension:
https://github.com/streamfoundations/react-dates-presets/

![687474703a2f2f73747265616d666f756e646174696f6e732e6769746875622e696f2f72656163742d64617465732d707265736574732f64656d6f2f64656d6f2e676966](https://user-images.githubusercontent.com/1241239/27733871-a8b7edd2-5d98-11e7-8a35-73a63f69f09a.gif)

**Comment by liubko** [comment] 2017-09-20 17:33
@mikesparr your solution might not work if you have calendar opened and part of the range isn't visible.

![1](https://user-images.githubusercontent.com/4257937/30658311-f2390334-9e42-11e7-97ee-ff04164ad86c.gif)

I click at `quarter` range, but only half of dates are highlighted. The problem is that when the dates aren't visible (`!isDayVisible(...)`), modifiers wouldn't be updated. 

https://github.com/airbnb/react-dates/blob/master/src/components/DayPickerSingleDateController.jsx#L442-L444

Would appreciate any help.

**Comment by danielone** [comment] 2017-10-10 16:46
Are presets now natively supported ?!

**Comment by derwaldgeist** [comment] 2017-11-09 21:28
Need this too, for weeks, months, and years.

**Comment by derwaldgeist** [comment] 2017-11-09 21:31
@sharq1 Your extension looks promising, but unfortunately it has no license attached to it.

**Comment by sharq1** [comment] 2017-11-10 07:07
@derwaldgeist it's MIT now. Cheers!

**Comment by majapw** [comment] 2017-11-29 00:55
This is somewhat addressed in that there is an example of how to do this at http://airbnb.io/react-dates/?react_perf=1&selectedKind=PresetDatePicker&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel

I don't think we will be shipping anything preset specific because it's already possible to implement it yourself with the API. Now there is better documentation of that. :)

**Closed by majapw** 2017-11-29 00:55 UTC
Labels: feature request, question
