### ISSUE TITLE
Updating orientation to HORIZONTAL hides the calendar.

### ISSUE THREAD

**Issue by rafinskipg** [airbnb/react-dates#358] opened 2017-03-07 00:22 UTC
Hi people from the internet.

When using the DayPickerRangeController and changing from VERTICAL to HORIZONTAL orientation the calendar is not render correctly. 

Until I hit some arrow, then it re-renders correctly.

I'm using  window.matchMedia to change the properties of the component.
```
updateDimensions(){
        if (window.matchMedia("(min-width: 1158px)").matches) {
        /* the viewport is at least 1158px pixels wide */
            this.setState({orientation: HORIZONTAL_ORIENTATION, numberOfMonths: 2})
        } else {
        /* the viewport is less than 1158px pixels wide */
            this.setState({orientation: VERTICAL_ORIENTATION, numberOfMonths: 1})
        }
    }
```

EDIT:

Found out that the element `transition-container transition-container--horizontal` is missing its height.

**Comment by majapw** [comment] 2017-03-17 20:36
Hi @rafinskipg, this seems like a bug with when we're calling `adjustDayPickerHeight()` inside of the `DayPicker`.

It should either get triggered by https://github.com/airbnb/react-dates/blob/master/src/components/DayPicker.jsx#L179-L182 or by https://github.com/airbnb/react-dates/blob/master/src/components/DayPicker.jsx#L191-L195 and it seems to be getting triggered by neither! Changing the orientation seems like a good reason to make sure that the height is recalculated properly.

If you want to put up a PR for this, feel free to. O/w I will get to it ASAP!

**Comment by danedavid** [comment] 2019-01-25 17:09
@majapw Can I take this up?

**Comment by ljharb** [comment] 2019-01-26 01:05
@danedavid please do!

**Comment by danedavid** [comment] 2019-01-26 11:17
@rafinskipg Could not reproduce the issue from my side. I did not notice anything when changing from `VERTICAL_ORIENTATION` to `HORIZONTAL_ORIENTATION`. Could you please provide a small working example to reproduce the issue, or atleast steps for reproducing the issue?

**Comment by mib32** [comment] 2019-07-25 12:47
@danedavid I was experiencing it when I was on v12, now updated to v20.2.5 - and the issue is gone.

**Comment by ljharb** [comment] 2019-07-25 14:10
Closing pending repro.

**Closed by ljharb** 2019-07-25 14:10 UTC
Labels: bug, pull request wanted
