### ISSUE TITLE
Clicking on buttons inside of the DayPickerRangeController does not handle focus correctly

### ISSUE THREAD

**Issue by Sumeet-Jain** [airbnb/react-dates#1420] opened 2018-10-16 23:55 UTC
I can't reproduce this on storybook since it uses iframes but can reproduce on airbnb.com. See attached gif

Whenever I click on the next month arrow, the focus of the page shifts to the body. However, when I use my keyboard to press the next button, focus is correctly to the next button within the calendar. I have been able to reproduce this for every date picker on airbnb, even the ones that directly import react dates, so its probably a react dates bug. If its airbnb specific, we can close this out. 

![react dates focus issue](https://user-images.githubusercontent.com/3238734/47053945-38856080-d164-11e8-8610-38702a55c54e.gif)

**Comment by erin-doyle** [comment] 2020-03-10 19:50
I believe this is the same is issue: https://github.com/airbnb/react-dates/issues/1065.  I'm going to close this issue as a duplicate of that one so we can consolidate the conversation but please feel free to reopen this if you feel it is different.

**Closed by erin-doyle** 2020-03-10 19:50 UTC

**Comment by ljharb** [comment] 2020-03-10 20:45
(duplicate of #1065, so the link is created)
