### ISSUE TITLE
componentWillUpdate will be renamed console warning

### ISSUE THREAD

**Issue by lainermeister** [airbnb/react-dates#1987] opened 2020-04-30 21:51 UTC
**react-dates version**
e.g. react-dates@18.3.1

I am implementing both the `DayPickerSingleDateController` and the `DayPickerRangeController` components, and I get these yellow warnings in my console.
```
react-dom.development.js:12357 Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: DayPicker, DayPickerSingleDateController
```
Is this a warning that I can suppress on my side? Or is this something that is being updated?

**Comment by ljharb** [comment] 2020-05-04 05:25
Duplicate of #1850. Duplicate of #1805. Duplicate of #1748.

**Closed by ljharb** 2020-05-04 05:25 UTC
