### ISSUE TITLE
Control not rendering properly

### ISSUE THREAD

**Issue by mike-hollibaugh** [airbnb/react-dates#1045] opened 2018-02-24 22:37 UTC
<img width="1048" alt="screen shot 2018-02-24 at 2 35 47 pm" src="https://user-images.githubusercontent.com/25161545/36635801-35f7118a-1970-11e8-8cc2-aa9ab008d80c.png">

**Comment by ljharb** [comment] 2018-02-24 22:39
Are you including the CSS?

**Comment by mike-hollibaugh** [comment] 2018-02-24 22:41
Her are the imports:
import React, { Component } from 'react';
import changeCaseObject from 'change-case-object';
import is from 'is'
import { render } from 'react-dom';
import 'react-dates/initialize'
import { DateRangePicker } from 'react-dates';
import { Button, Checkbox } from 'react-bootstrap';
import URLSearchParams from 'url-search-params'

import { apiCall } from 'app/api'
import Message from 'app/common/Message';
import moment from 'moment';
import Dropdown from 'app/common/Dropdown';
import SavedSearchInput from 'app/common/SavedSearchInput';
import { InteractionBar } from 'app/reusable/InteractionBar/index';
import { Notification } from 'app/reusable/Notification/index';
import { ConfirmModal } from 'app/reusable/ConfirmModal/index';
import * as API from './api';
import * as chart from './chart';

import 'react-dates/lib/css/_datepicker.css';
import './style';

**Comment by majapw** [comment] 2018-02-24 22:50
This is due to the missing css in the latest version. I need to rerun and
prerelease but I would peg to 16.3 0.

**Comment by ljharb** [comment] 2018-02-24 22:51
Closing as a duplicate of #1044.

**Comment by mike-hollibaugh** [comment] 2018-02-24 22:52
I have tried several different version since we found this problem yesterday and they are all doing the same thing.

**Comment by ljharb** [comment] 2018-02-24 22:53
@mike-hollibaugh 16.3.0 has the same problem for you?

**Comment by majapw** [comment] 2018-02-24 22:53
Including 16.3.0? That one should be okay.

**Comment by mike-hollibaugh** [comment] 2018-02-24 22:54
Ill give it a go.

**Comment by mike-hollibaugh** [comment] 2018-02-24 23:01
We are having the same issue with 16.3.0 and 16.0.0.

**Comment by titanve** [comment] 2018-02-25 01:06
Hello everyone! 

Any news regarding this issue???

**Comment by mike-hollibaugh** [comment] 2018-02-25 01:28
I had to rollback to version 15.4.3 to get it to work again.

**Comment by mike-hollibaugh** [comment] 2018-02-25 01:28
Sorry, 15.5.3

**Comment by TomBurnettUK** [comment] 2018-02-25 01:43
Are you sure you're fixing it to a single version (i.e. you haven't left the preceding ^ in the version number in your package.json)?  I only suggest this because I *cough* spent the last half hour trying different minor and patch versions before realising I was just installing 16.3.3 over and over.

16.3.0 works fine for me (doesn't have the empty _datepicker.css).

**Comment by mike-hollibaugh** [comment] 2018-02-25 01:45
Hi tom, here is waht is in packages.json     "react-dates": "^15.5.3",
Which now is working

**Comment by mike-hollibaugh** [comment] 2018-02-25 01:45
Should I remove that caret?

**Comment by TomBurnettUK** [comment] 2018-02-25 01:52
Yeah.  Because that specifies you want to automatically update to the latest minor version.  If you delete it, you'll get the specific version you want.

[https://docs.npmjs.com/getting-started/semantic-versioning#semver-for-consumers](url)

**Comment by mike-hollibaugh** [comment] 2018-02-25 01:58
Thanks Tom.  Works like a charm

**Comment by majapw** [comment] 2018-02-25 02:01
Okay that makes more sense! Really sorry about the broken version. I'm not
home right now but I'll fix it when I get there and also introduce a
measure to prevent it in the future!

**Comment by majapw** [comment] 2018-02-25 07:10
16.3.4 should be out and include a css file and stuff ==> https://unpkg.com/react-dates@16.3.4/lib/css/_datepicker.css. This means we can go back to careting things. Sorry for the breakage.

Will follow up with a check for the css file separately.

**Closed by majapw** 2018-02-25 07:10 UTC
