### ISSUE TITLE
The date changes to the last day of the week after second calendar open

### ISSUE THREAD

**Issue by dominikkurbiel** [airbnb/react-dates#1800] opened 2019-09-25 11:16 UTC
**react-dates version**
e.g. react-dates@21.1.0

**Describe the bug**
This bug is on all Datepickers.

1. Open picker and select the date (different than the end of the week - yeah that's important)
    F.e: I'm selecting 26 september.
2. Open datepicker again.
3. On the input date changes to September 28, but on calendar there is still 26. So the date CHANGES automatically to the last day of the week
4. Close calendar without selecting the date and open again. Now you have changed date on calendar too.

Just go into link below or to any example in Storybook and try it on you own :)

**Is the issue reproducible in Storybook?**
You can see this on all examples in Storybook
EXAMPLE: https://airbnb.io/react-dates/?path=/story/sdp-input-props--default

**Comment by mmarkelov** [comment] 2019-09-25 11:25
Duplicate of #1799 #1795

**Closed** 2019-09-25 11:57 UTC
