### ISSUE TITLE
Warning: componentWillReceiveProps has been renamed, and is not recommended for use.

### ISSUE THREAD

**Issue by ranneyd** [airbnb/react-dates#1805] opened 2019-09-27 01:36 UTC
**react-dates version**
react-dates@21.1.0

**Describe the bug**
Since React@16.9 any component that uses `componentWillReceiveProps` produces a console warning:

```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: DateInput, OutsideClickHandler
```

Note at the bottom it says `Please update the following components: DateInput, OutsideClickHandler`. However, some grep-ing shows:
```
>grep componentWillReceiveProps -r .
./components/CalendarMonth.jsx:  componentWillReceiveProps(nextProps) {
./components/DayPickerKeyboardShortcuts.jsx:  componentWillReceiveProps(nextProps) {
./components/DayPickerSingleDateController.jsx:  componentWillReceiveProps(nextProps) {
./components/DayPickerRangeController.jsx:  componentWillReceiveProps(nextProps) {
./components/DayPicker.jsx:  componentWillReceiveProps(nextProps) {
./components/CalendarMonthGrid.jsx:  componentWillReceiveProps(nextProps) {
./components/DateInput.jsx:  componentWillReceiveProps(nextProps) {
```

The fix should be as simple as pre-pending `UNSAFE_` to those functions and re-building

**Source code (including props configuration)**
Note that I'm using react hooks for the state and I'm converting my dates to moments on-the-fly:
```
const DATE_FORMAT_MOMENT = "YYYY-MM-DD";

<DateRangePicker
  startDate={moment(dates.start)}
  endDate={moment(dates.end)}
  startDateId="start"
  endDateId="end"
  onDatesChange={({ startDate, endDate }) => {
    if (startDate && endDate) {
      setDates({
        start: startDate.format(DATE_FORMAT_MOMENT),
        end: endDate.format(DATE_FORMAT_MOMENT)
      });
    }
  }}
  focusedInput={focusedDate}
  onFocusChange={focusedDate => setFocusedDate(focusedDate)}
/>
```

**Desktop (please complete the following information):**
 - Mac OS 10.14.6
 - Chrome 77.0.3865.90

**Comment by ljharb** [comment] 2019-09-27 05:24
Duplicate of #1748.

**Closed by ljharb** 2019-09-27 05:24 UTC
