### ISSUE TITLE
FR: onDatesChangeFinal

### ISSUE THREAD

**Issue by amivag** [airbnb/react-dates#1129] opened 2018-04-23 10:22 UTC
Needing a callback for when the user has finished selecting both dates (both start and end).

onDatesChange fires separately on start and end selections, not extremely helpful.

onClose was a good workaround, except it doesn't fire with ClearDates.

**Comment by ljharb** [comment] 2018-04-23 14:34
Duplicate of #1070.

**Comment by majapw** [comment] 2018-04-23 17:13
I'll close this and continue the conversation on #1070

**Closed by majapw** 2018-04-23 17:13 UTC
