### ISSUE TITLE
Warnings for ComponentWillReceiveProps & ComponentWillUpdate

### ISSUE THREAD

**Issue by nitish-arora** [airbnb/react-dates#2183] opened 2022-02-22 07:07 UTC
**react-dates version**
react-dates@21.8.0

**Describe the bug**
Getting warnings for UNSAFE lifecycle methods. Could you please update this with the latest lifecycles.

**Comment by ljharb** [comment] 2022-02-22 07:07
Duplicate of #1748.

**Closed as completed by ljharb** 2022-02-22 07:07 UTC
