### ISSUE TITLE
Cannot see blinking cursor when typing into date inputs

### ISSUE THREAD

**Issue by chris-pearce** [airbnb/react-dates#618] opened 2017-07-06 00:35 UTC
Due to the inputs (`.DateInput__input`) having `opacity: 0;` set:

```css
.DateInput__input {
    opacity: 0;
    position: absolute;
    top: 0;
    left: 0;
    border: 0;
    height: 100%;
    width: 100%;
}
```

You do not see the blinking cursor as you type into the overlaying `<div>` element (`.DateInput__display-text`) making it practically unusable as you cannot see where you're typing.

The heavy handed workaround is to make the inputs `readonly` via the `readOnly` prop, however, disabling a user from being able to enter their own dates hinders the overall UX.

**Comment by ConAntonakos** [comment] 2017-07-06 20:15
This seems to be related to https://github.com/airbnb/react-dates/issues/276.

**Comment by majapw** [comment] 2017-07-06 20:34
Yeah let's close this as a duplicate of #276 and move discussion there.

It's been on my roadmap for a while to add this behavior in somehow, but unfortunately my bandwidth has been fairly low. I have some ideas... but have not really had the time to bring any of them to fruition, unfortunately.

**Closed** 2017-07-06 20:43 UTC
Labels: duplicate
