### ISSUE TITLE
`react-dates/lib/css/_datepicker.css` breaking when using `sass` with CRA 4

### ISSUE THREAD

**Issue by m-nathani** [airbnb/react-dates#2152] opened 2021-10-16 05:19 UTC
**react-dates version**
`react-dates@21.8.0`

**Describe the bug**

I am using `CRA 4` and using `react-dates` intensively in my project... i was using `node-sass` before to import css from react-dates and it was working..

```style
@import '~react-dates/lib/css/_datepicker.css';
```

However, recently i moved to `sass` and i found out that css file is breaking when importing the css file in my source code 

```
@import '~react-dates/lib/css/_datepicker';
``` 

**Error in css file**

Here is the error i am facing importing `react-dates` css file using  `sass`

```style
This function isn't allowed in plain CSS. ╷ 152 
│
    color: darken(#cacccd,10%);
│ ^^^^^^^^^^^^^^^^^^^ ╵
 
  node_modules/react-dates/lib/css/_datepicker.css 152:10 @import
```

**Desktop (please complete the following information):**

 - OS: [Linux]
 - Browser [chrome]
 - Version [94.0.4606.71 (Official Build) (64-bit)]

**Additional context**

here is discussion i had on official sass `twitter` account regarding this issue and what they identified as well:

https://twitter.com/SassCSS/status/1449093432060698624?s=20

**Comment by ljharb** [comment] 2021-10-16 05:25
This is fixed but not yet released. Duplicate of #2081.

**Closed by ljharb** 2021-10-16 05:25 UTC

**Comment by m-nathani** [comment] 2021-11-26 08:41
Its this package maintained or not ? as this is a basic fix for styles not yet release since ages... ?
