### ISSUE TITLE
Official support for Moment has (finally) been discontinued

### ISSUE THREAD

**Issue by davea38** [airbnb/react-dates#2044] opened 2020-09-17 12:26 UTC
I'd love to use this library, but moment is too heavy. Finally it's been officially discontinued... could I please request you change to date-fns?!

[Moment repo](https://github.com/moment/moment/)

**Comment by ljharb** [comment] 2020-09-17 20:16
This is a duplicate of #208, in which it's explained that we'll be on moment until Temporal is stage 3, at which point we'll migrate to that.

**Closed by ljharb** 2020-09-17 20:16 UTC

**Comment by davea38** [comment] 2020-09-17 23:58
Thanks for the clarification 👍
