### ISSUE TITLE
Focus on a date when calendar is opened

### ISSUE THREAD

**Issue by SergeyShablenko** [airbnb/react-dates#1319] opened 2018-08-21 09:02 UTC
I\`m using DayPickerSingleDateController and custom input implementation, on input focus I\`m showing DayPickerSingleDateController and on input change I`m looking for the closest date and then set this date to DayPickerSingleDateController as date prop.

Date is selected, but calendar does not 'scroll' to that date

**Comment by majapw** [comment] 2018-08-21 15:41
Weird! Several people opening the same issue at the same time! 

This is a duplicate of https://github.com/airbnb/react-dates/issues/1320 and https://github.com/airbnb/react-dates/issues/1257. Let's track on #1320 actually since it has the most succinct summary of this issue.

**Closed** 2018-08-21 15:41 UTC
Labels: duplicate
