### ISSUE TITLE
Prevent Navigation to Dates in the Past.

### ISSUE THREAD

**Issue by AntiFish03** [airbnb/react-dates#400] opened 2017-03-23 22:27 UTC
Is there a good way to prevent the Previous Navigation Button from scrolling the calendar into the past?  In playing around with it I can get that functionality by adding 
``` javascript
onPreviousMonthClick(e) {
  ...
  const newMonth = this.state.currentMonth.clone().subtract(1, 'month');
  if (preventPastMonthNav && newMonth.isBefore(moment().startOf('month'))) {
    return;
  }
  ...
}
```

But I wasn't necessarily sure if that was the best way to add this functionality. And I would assume that I am not the only one that might want this functionality and it could also be added to prevent Navigation into the future.  I am happy to submit a PR for this.

**Comment by AntiFish03** [comment] 2017-03-27 21:21
@majapw, Can you give me some guidance on this?

**Comment by majapw** [comment] 2017-07-21 18:53
Closing in favor of #631

**Closed by majapw** 2017-07-21 18:53 UTC
Labels: duplicate

**Comment by ljharb** [comment] 2017-07-21 19:55
Duplicate of #631
