### ISSUE TITLE
Closing issue with portal ONLY on iOS

### ISSUE THREAD

**Issue by timhecker** [airbnb/react-dates#328] opened 2017-02-13 16:06 UTC
Hi,
I can't close datepicker with `withPortal: true` on latest iOS, both Safari and Chrome, as you can see on the screenshot. I think that something goes in focus and doesn't allow me to ESC from portal. Can you help me?

![react-dates-screen](https://cloud.githubusercontent.com/assets/3533765/22890920/072d8760-f20e-11e6-955e-01d907518780.jpeg)

**Comment by majapw** [comment] 2017-02-13 20:11
This is a duplicate of https://github.com/airbnb/react-dates/issues/246. Let's continue tracking this issue there.

**Closed** 2017-02-13 20:11 UTC
Labels: duplicate
