### ISSUE TITLE
Edit date in input field

### ISSUE THREAD

**Issue by jpiulac** [airbnb/react-dates#79] opened 2016-09-13 10:41 UTC
It would be great to be able to directly edit the date in the input field and have the date picker reflect the changes.

Avoids having to navigate many months, years etc...

This example seems to work well.
http://pushtell.github.io/react-bootstrap-date-picker/

**Comment by majapw** [comment] 2016-09-13 14:28
You can, actually. Although the design doesn't especially indicate this right now. If you try typing a date in the `L` format (`MM/DD/YYYY`) or in ISO format (`YYYY-MM-DD`), it should accept it and update the calendar appropriately. ... I should change the placeholder to indicate this. :)

**Comment by majapw** [comment] 2016-09-16 00:24
Since this isn't actually an issue, I'm going to close it. If you have any issues about specific implementation, we can open those as a follow up. :)

**Closed by majapw** 2016-09-16 00:24 UTC

**Comment by timhwang21** [comment] 2017-01-26 17:01
So I'm testing this in the Storybook example, and it doesn't seem to work:

![](https://i.gyazo.com/1fe03338982d390e5e1025b08b52bd52.gif)

Is this a regression, or has this feature been dropped? Thanks!

**Comment by majapw** [comment] 2017-01-26 21:35
@timhwang21 Well fudge. Nope, that's a regression! Probs the change in input value (I thought I had tested that!). Will patch immediately.

**Comment by VikasPrasad23** [comment] 2017-09-20 01:30
I am using airbnb/react-dates for user to select or type start and end date. However I am not able to edit date fields. I can select dates but not able to type into the date fields.

I tried reading below links but no luck so far https://github.com/airbnb/react-dates http://airbnb.io/react-dates/?selectedKind=DateRangePicker%20%28DRP%29&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel https://github.com/airbnb/react-dates/issues/79

In my package.json I have "react-dates": "^12.6.0"

I am using below props and running it in Chrome.

<DateRangePicker
        className="clientsPaging"
        displayFormat={"YYYY-MM-DD"}
        startDate={this.state.startDate} // momentPropTypes.momentObj or null,
        endDate={this.state.endDate} // momentPropTypes.momentObj or null,
        onDatesChange={this.datesChanged} // PropTypes.func.isRequired,
        isOutsideRange={() => false}
        focusedInput={this.state.focusedInput} // PropTypes.oneOf([START_DATE, END_DATE]) or null,
        onFocusChange={focusedInput => this.setState({ focusedInput })} // PropTypes.func.isRequired,
      />

**Comment by elenaHristova** [comment] 2018-01-29 09:20
Hi @VikasPrasad23 ,
Did you find a fix for this using 12.6.0 or did you have to update the version?

**Comment by JetUni** [comment] 2018-03-24 17:47
I don't think this issue should be closed. This isn't working in the storybook.

> You can, actually. Although the design doesn't especially indicate this right now. If you try typing a date in the L format (MM/DD/YYYY) or in ISO format (YYYY-MM-DD), it should accept it and update the calendar appropriately. ... I should change the placeholder to indicate this. :)

I've tried entering a date in the `L` format and ISO format and neither one updates the calendar appropriately

**Comment by majapw** [comment] 2018-03-24 19:27
@JetUni Can you share a gif of the behavior? Also, browser info and react-dates version would be useful. Is this in your app or in storybook?

**Comment by majapw** [comment] 2018-03-24 19:28
@JetUni Also let's open a new issue if you see this happening in the latest. :)

**Comment by awongh** [comment] 2018-07-27 03:16
@majapw I am still seeing this issue. 

Specifically in the storybook, the single date picker with the default date set doesn't have the correct behavior when trying to type in the input.

When you enter anything into the input, the cursor moves to the end of the text.

There are other problems with the input, like when you finally enter a valid date, the input loses focus and the picker window closes.

http://airbnb.io/react-dates/?selectedKind=SDP%20-%20Input%20Props&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by Phibedy** [comment] 2018-12-19 18:05
Same for me as @majapw already said.
* If you type in `01.01.2018` the calendar closes
* If you type in  `01.1.2018` the resulting date is null

version: 18.3.1

**Comment by olive49** [comment] 2020-12-14 10:59
Is there a way to type the date in (DD/MM/YYYY) format and be reflected in the calendar?

**Comment by VickTor61** [comment] 2021-08-05 12:33
I'm using react-dates to show the date in my app. when i manually try to change the date, i get this warning in my chrome browser console 
```
react_devtools_backend.js:2574 Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
```
I tried finding my way around it and to no avail so i got here.
This is my app code using the the singleDatePicker
```
 <SingleDatePicker
          date={description.createdAt}
          onDateChange={onDateChange}
          focused={description.calenderFocused}
          onFocusChange={onFocusChange}
          numberOfMonths={1}
        />
```

**Comment by ljharb** [comment] 2021-08-05 13:45
@VickTor61 rhat warning is expected and currently unavoidable. See #1748

**Comment by VickTor61** [comment] 2021-08-05 14:56
> @VickTor61 rhat warning is expected and currently unavoidable. See #1748


Wow. That means i can't use the react-dates library right now?

**Comment by ljharb** [comment] 2021-08-05 15:14
@VickTor61 of course not. it's just a warning. it means you just ignore it.

**Comment by VickTor61** [comment] 2021-08-05 21:56
> @VickTor61 of course not. it's just a warning. it means you just ignore it.

The things is i'm trying to connect my react state to the react-dates library and when i try to change the date, it shows me that warning. And it doesnt update the date.
I tried two different libraries for same purpose and both worked. So i felt i couldn't use the library until you guys update the source code hence the purpose of my message

**Comment by ljharb** [comment] 2021-08-05 22:15
@VickTor61 it should still work just fine. perhaps you're using react 17, which we don't support yet? (see #2105)

**Comment by VickTor61** [comment] 2021-08-05 22:30
No m using react 18 i just started the build few days ago with create react app so m using the latest react version

**Comment by ljharb** [comment] 2021-08-06 00:49
@VickTor61 react 18 isn't out yet - but either way, react-dates does not support react > 16 yet.

Run `npm ls`, and it will tell you that your dependency graph is invalid.

If you have any further comments, please file a new issue, since all of this is off topic for this issue.

**Comment by VickTor61** [comment] 2021-08-06 00:52
Okay then. I will find my way around it. Thanks though for your reply. Came in handing
