### ISSUE TITLE
Allow user to select date range from a predefined set of date ranges

### ISSUE THREAD

**Issue by prashand** [airbnb/react-dates#853] opened 2017-11-26 05:02 UTC
This is a feature request. Add an option to set predefined date ranges the user can select from. This feature is extremely useful in reporting.

![image](https://user-images.githubusercontent.com/5242391/33237279-cd634372-d294-11e7-9c3f-268082f32a26.png)

This feature is available in the [Date Range Picker for Bootstrap](http://www.daterangepicker.com/)  by Improvely.

**Comment by majapw** [comment] 2017-11-28 00:53
This is a duplicate of https://github.com/airbnb/react-dates/issues/29

It's already possible to do this functionality because the DRP is fully controlled by adding some buttons inside the `renderCalendarInfo` prop (which takes a function that returns a node) that would set start and end date appropriately.

That being said I think exporting a `PresetDateRangePicker` component with that prop already set up seems reasonable.

**Comment by majapw** [comment] 2017-11-28 20:00
I'm gonna close in favor of #29 (and in order to pare down the number of issues a bit)

**Closed by majapw** 2017-11-28 20:00 UTC
Labels: duplicate, feature request

**Comment by prashand** [comment] 2017-12-02 10:25
Thanks @majapw. Did not see the renderCalenderInfo prop or the PresetDateRangePicker example in the docs.

**Comment by gouthamr22** [comment] 2017-12-29 18:51
how did you focus to the selected date range when u selected custom date range.

**Comment by majapw** [comment] 2018-01-02 18:56
@gouthamr22 can you open a new issue and elaborate on your problem?

Focusing in the calendar is done automatically (there's not outside control available). If you focus back on the calendar assuming it remains open, the last focused day should still be focused. If you close it and reopen it, the start date is focused (I believe).

**Comment by gouthamr22** [comment] 2018-01-02 19:24
@majapw  i did open a new issue for this. please check, https://github.com/airbnb/react-dates/issues/929
