### ISSUE TITLE
SingelDatePicker before today

### ISSUE THREAD

**Issue by DrogoNevets** [airbnb/react-dates#2189] opened 2022-03-21 13:36 UTC
**react-dates version**
react-dates@21.8.0

**Describe the bug**
SIngleDatePicker has no prop `minDate` or similar. Meaning I allow a date in the past. Use case, date of birth.

**Source code (including props configuration)**
```
<SingleDatePicker 
      date={startDate}
      id="date"
      focused={focussed}
      onFocusChange={(e) => setFocussed(e.focused)}
      onDateChange={(date) => console.log(date)}
    />
```

**Screenshots/Gifs**
If applicable, add screenshots or gifs to help explain your problem.

**Is the issue reproducible in Storybook?**
[Single date picker](https://react-dates.github.io/react-dates/?path=/story/sdp-input-props--default)

**Additional context**
I am sure I have missed something, as seems like a very common use case

**Comment by ljharb** [comment] 2022-03-21 13:48
Duplicate of #2092; see https://github.com/react-dates/react-dates/issues/2092#issuecomment-799323540

**Closed as completed by ljharb** 2022-03-21 13:48 UTC
Labels: question
