### ISSUE TITLE
Change calendar system to Jalali canendar

### ISSUE THREAD

**Issue by cyclops24** [airbnb/react-dates#447] opened 2017-04-14 03:06 UTC
I want to user `react-dates` as a Persian datepicker. Persians use another calendar system that called `jalali calendar`. We have a popular library called [moment-jalaali](https://momentjs.com/docs/#/plugins/jalaali/) that works perfectly as a `moment` plug-in.
Now my question is that: How we can use `jalali calendar` system with `react-dates`?
I try below code, but it's just change locale and strings not entire calendar system.

```
import React, { Component } from 'react';
import './App.css';
import moment from 'moment-jalaali';
import { DateRangePicker, SingleDatePicker, DayPickerRangeController } from 'react-dates';
import 'react-dates/lib/css/_datepicker.css';

class App extends Component {

  render() {
    moment.loadPersian(); // >>>>>>>>>> This change locale to Persian successfully but how to change calendar system?
    return (
      <div className="App">

        <SingleDatePicker
          date={moment()}
          onDateChange={date => console.log(date)} // PropTypes.func.isRequired
        focused={true}
          onFocusChange={({ focused }) => console.log(focused)} // PropTypes.func.isRequired
        />

      </div>
    );
  }
}

export default App;
```

This is output screen shot for above code you can see that calendar system is wrong:
![jalali_1](https://cloud.githubusercontent.com/assets/8266479/25031858/f7fb2940-20e4-11e7-8074-82a1a3bbc653.png)

**Comment by cyclops24** [comment] 2017-04-14 03:18
I think it's related to #259

**Comment by cyclops24** [comment] 2017-04-15 11:09
I added "renderMonth" and a simple example as a start point ( #449 ) for adding Persian calendar. Some small problem still exist in completely support Persian calendar (like days order, ...). But I think we can do this by add some other PR.

**Comment by majapw** [comment] 2017-05-02 19:57
Fixed in v10.2.0!

**Closed** 2017-05-02 19:57 UTC

**Comment by mpourismaiel** [comment] 2017-06-07 12:35
`renderMonth` and `renderDay` fixes the locale problem but the issue with the calendar itself still stands. 

![calendar](https://image.ibb.co/drxmav/Clipboard_image_2017_06_07_17_03_22.png)

First of the month in the calendar is marked 11, which is 11th of the respective month in Jalali while it should obviously be 1. Am I missing something?

**Comment by ImanMh** [comment] 2017-06-17 16:40
@mpourismaiel Have you found any solutions?

**Comment by mpourismaiel** [comment] 2017-06-17 18:42
@ImanMh They thought the issue was that there was no way to change the locale for month names which actually was another bug.

**Comment by ljharb** [comment] 2017-06-17 18:58
@ImanMh @mpourismaiel please file a new issue if there’s still a problem with the jalali calendar :-)

**Comment by mpourismaiel** [comment] 2017-06-17 19:10
The problem is as the topic says. Calendar is set to Jalali but the display is not correct. Should I create a new task for that?

**Comment by ljharb** [comment] 2017-06-17 19:42
Yes, that'd be great.

**Comment by ImanMh** [comment] 2017-06-19 13:36
Sounds grate, if this issue is fixed many more people will start replacing their code with this date picker.  Please notify people at this thread if this issue is fixed.

**Comment by melinapazoki** [comment] 2017-10-15 08:42
<DateRangePicker
                            monthFormat={'jMMMM'}
                            isRTL={true}
          />

**Comment by melinapazoki** [comment] 2017-10-15 08:43
`        <DateRangePicker
                            monthFormat={'jMMMM'}
                            isRTL={true}
                            />`

**Comment by VeRJiL** [comment] 2022-02-20 05:18
Guys, any updates?
Can we use this awesome library for Jalali Calendar ?
