### ISSUE TITLE
prevent range selection if selected date is blocked

### ISSUE THREAD

**Issue by KhaustovN1ck** [airbnb/react-dates#478] opened 2017-04-28 07:40 UTC
Hi, I wonder if it's possible to prevent selection, if there are some days blocked inside this selection (example below)
![image](https://cloud.githubusercontent.com/assets/14973843/25518993/c750ee9a-2bfe-11e7-993d-09232c79de1e.png)

**Comment by majapw** [comment] 2017-05-03 16:39
This is a duplicate of https://github.com/airbnb/react-dates/issues/23. So I'm going to close it in favor of that. We want this behavior, but haven't had the change to implement it yet. Before, it was also... somewhat impossible with the way the modifiers were structured. I think it is slightly more possible now with the new architecture in v11, so I will probably be exploring this in the near future.

**Closed by majapw** 2017-05-03 16:39 UTC
Labels: duplicate

**Comment by hemanth-sp** [comment] 2018-09-05 05:56
is it sloved??????/
