### ISSUE TITLE
Future support for react-dates?

### ISSUE THREAD

**Issue by pbspot15** [airbnb/react-dates#2076] opened 2021-01-04 10:14 UTC
Is there going to be a future support for react-dates? I see that the last release had happened almost a year ago (30 Jan 2020). 

Moreover, react-dates still uses MomentJS and therefore it is a tightly coupled dependency. However, according to folks at MomentJS, seems it is now a legacy project with only maintenance and no active development. So are there plans to migrate react-dates to using a different date-time library?

![Screenshot 2021-01-04 at 3 53 20 PM](https://user-images.githubusercontent.com/60482833/103524500-c95fc800-4ea5-11eb-84f0-97590b3ed9e6.png)

**Comment by ljharb** [comment] 2021-01-04 19:12
Despite moment.js's announcement, it remains the defacto standard for the ecosystem until Temporal is stage 3, and a viable production-ready polyfill exists (neither of which is the case yet).

At that time, react-dates will switch to Temporal and drop moment.js.

This is a duplicate of #208, and also a duplicate of #2044.

**Closed by ljharb** 2021-01-04 19:12 UTC

**Comment by pbspot15** [comment] 2021-01-04 19:18
@ljharb what about new releases for react-dates? I am sure there are lots of fixes that have gone in since Jan 30 2020. Is there any timeline for that?

**Comment by ljharb** [comment] 2021-01-04 19:36
That's a different question; at the moment, I don't have the ability to push directly to master (required for a clean release) and Airbnb employees have not been maintaining the package for awhile.

I have a workaround available when it becomes urgent - but I'm saving that for "the last release prior to Temporal", and "the first release with Temporal".
