### ISSUE TITLE
Calendar icon for <SingleDatePicker/> too?

### ISSUE THREAD

**Issue by t47io** [airbnb/react-dates#368] opened 2017-03-10 05:44 UTC
Hi, I found it would be desirable (at least for my use case) to support 
```
  showDefaultInputIcon: PropTypes.bool,
  customInputIcon: PropTypes.node,
```
 for `<SingleDatePicker/>` as well (currently only available for `<DateRangePicker/>`). Just want to hear if this would be agreed. And I can spend some time to dive in and make a PR. Thoughts?

**Comment by majapw** [comment] 2017-03-17 20:16
Hi @t47io, we'd love for this to be on the `SingleDatePicker` as well! Just haven't had any time to implement it. :) If you would like to do that, we would def accept a PR.  This issue is a duplicate of https://github.com/airbnb/react-dates/issues/292 so I'll close this one and assign you to that issue if you don't mind!

**Comment by t47io** [comment] 2017-03-23 02:38
@majapw will try to find some time on this~

**Comment by JemarJones** [comment] 2017-05-16 20:55
@t47io hows the progress?

**Comment by t47io** [comment] 2017-05-17 02:44
@JemarJones Sorry wasn't able to spare time recently. Kudos to @b0gok

**Closed** 2017-05-18 20:36 UTC
Labels: feature request, pull request wanted
