### ISSUE TITLE
Warning: This synthetic event is reused for performance reasons

### ISSUE THREAD

**Issue by mhluska** [airbnb/react-dates#936] opened 2018-01-02 20:46 UTC
I get the following warning when navigating with left/right arrow keys on the picker:

```
Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the method `stopPropagation` on a released/nullified synthetic event. This is a no-op function. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.
```

The full stack trace:

```
__stack_frame_overlay_proxy_console__ | @ | proxyConsole.js:56
-- | -- | --
  | console.(anonymous function) | @ | console.js:32
  | printWarning | @ | warning.js:33
  | warning | @ | warning.js:57
  | warn | @ | react-dom.development.js:1798
  | get | @ | react-dom.development.js:1792
  | onKeyDown | @ | DateInput.js:218
```

Looks like there's a `stopPropagation` call at `DateInput.js:218`.

**Comment by erin-doyle** [comment] 2018-01-02 20:52
I think this should be fixed when we get Pull Request #916 merged.  Either way this is a duplicate of Issue #514 .

**Closed by erin-doyle** 2018-01-02 20:52 UTC
