### ISSUE TITLE
Blinking cursor in mobile when using DateRangePicker

### ISSUE THREAD

**Issue by yaswakarthi** [airbnb/react-dates#1485] opened 2018-12-10 06:59 UTC
Hi,

I am using "react-dates": "^18.1.1"

I am using DateRangePicker with withFullScreenPortal option. Once touch the input I am gettting a blinking cursor. It doesnt create a problem in desktop but it is creating a problem in mobile.

when I am using readOnly attribute, Touchinput is not working. But it works Old version only.( "react-dates": "12.2.2" version)

How to disable keyboard with calendar using DateRangePicker?
Is there any way to avoid the blinking cursor in mobile when using latest version of react-dates?

 <DateRangePicker
                    onDatesChange={this.onDatesChange}
                    onFocusChange={this.onFocusChange}
                    focusedInput={focusedInput}
                    orientation="vertical"
                    withFullScreenPortal
                    readOnly
                   />

**Comment by majapw** [comment] 2018-12-18 05:05
@yaswakarthi does setting the `readOnly` prop to `true` solve your issue?

**Comment by majapw** [comment] 2018-12-18 05:51
Actually I'm going to mark this as a duplicate of #1476 and continue the conversation on that issue.

**Closed by majapw** 2018-12-18 05:51 UTC
Labels: duplicate, question
