### ISSUE TITLE
How to translate this damn calendar into Russian

### ISSUE THREAD

**Issue by sxavi** [airbnb/react-dates#1636] opened 2019-05-07 09:48 UTC
как перевести этот календарь на русский язык, потратил уже кучу времени и все в пустую, неужели нельзя создать пропсы куда бы я передавал массив с названиями дней недели и месяцами

**Comment by ljharb** [comment] 2019-05-07 15:53
from google translate:
> how to translate this calendar into Russian, has already spent a lot of time and everything is empty, is it really impossible to create props where I would pass an array with the names of the days of the week and months

Duplicate of #327, i think?

**Comment by saschb2b** [comment] 2019-05-28 12:11
Setting it via `moment.locale()` doesn't work every time. For me just importing the wanted language was enough. For Russian `import 'moment/locale/ru';`

**Closed** 2019-05-29 05:27 UTC

**Comment by ozil07** [comment] 2019-06-05 22:55
Ты лучший друг!!!!!!

**Comment by ozil07** [comment] 2019-06-05 22:55
> Setting it via `moment.locale()` doesn't work every time. For me just importing the wanted language was enough. For Russian `import 'moment/locale/ru';`

Ты лучший друг!!!!!!

**Comment by mr-devboy** [comment] 2019-09-04 11:00
> Setting it via `moment.locale()` doesn't work every time. For me just importing the wanted language was enough. For Russian `import 'moment/locale/ru';`

Thank you

**Comment by ghost** [comment] 2022-09-20 12:29
> Setting it via `moment.locale()` doesn't work every time. For me just importing the wanted language was enough. For Russian `import 'moment/locale/ru';`

THANK YOU BOSS

**Comment by Fuur** [comment] 2024-06-19 16:34
> Setting it via `moment.locale()` doesn't work every time. For me just importing the wanted language was enough. For Russian `import 'moment/locale/ru';`

Thank you very much 🫶🏼
