### ISSUE TITLE
Add time selection support

### ISSUE THREAD

**Issue by MathieuDebit** [airbnb/react-dates#396] opened 2017-03-23 10:53 UTC
Hi,

I don't find anything about hours/minutes/seconds selection in pickers. Do you plan to add this feature?

Thanks!

**Comment by DavidatSplitPeak** [comment] 2017-03-26 22:26
Or has anyone explored a time picker variation that works like the date selection?

**Comment by ljharb** [comment] 2017-03-27 01:04
Duplicate of #255

**Closed by ljharb** 2017-03-27 01:04 UTC
