### ISSUE TITLE
Hide arrow buttons on DateRangePicker

### ISSUE THREAD

**Issue by mrmuhammadali** [airbnb/react-dates#723] opened 2017-09-23 08:17 UTC
Hi,
Is there any way to hide arrow buttons on DateRangePicker?
I'm enabling only last 30 days on Calendar so I dont need the navigation buttons.
Thanks

**Comment by ljharb** [comment] 2017-09-23 16:35
The "last 30 days" could potentially span up to three months. How many months are you displaying?

**Comment by mrmuhammadali** [comment] 2017-09-24 09:08
I'm displaying 2 months.

**Comment by majapw** [comment] 2017-09-25 17:03
I think this is a dupe of https://github.com/airbnb/react-dates/issues/339, but the short answer is that there is currently no way to disable the month navigation based on a certain range. I would be open to accepting a PR for this behavior.

**Comment by ljharb** [comment] 2017-09-25 17:54
Closing as a duplicate.

**Closed by ljharb** 2017-09-25 17:54 UTC
Labels: duplicate
