### ISSUE TITLE
Hide months outside range

### ISSUE THREAD

**Issue by iamvanja** [airbnb/react-dates#991] opened 2018-01-30 17:47 UTC
First of all, thanks for the awesome component! 
I would like to allow calendar input from 2017-01-01 until today.

I am able to accomplish this using `isOutsideRange` method. 
```js
  isOutsideRange (day) {
    const isBeforeStart = day.isBefore(moment('2017-01-01'))
    const isAfterToday = day.isAfter(moment().add(1, 'days'))

    return isBeforeStart || isAfterToday
  }
```

This however still displays all months (before 2017 and after today), regardless of the fact that every day in those months is disabled. 

Is there a way to not display those months?

Thanks

**Comment by majapw** [comment] 2018-01-30 17:52
I think this is a duplicate of https://github.com/airbnb/react-dates/issues/339. I'm gonna close in favor of that.

We've unfortunately not had the bandwidth yet to take a look at this, but would be happy to accept a PR either to disable or hide month navigation outside of a certain range. :)

**Closed by majapw** 2018-01-30 17:52 UTC
