### ISSUE TITLE
Tab on Edge/Firefox doesn't move the cursor to the next input

### ISSUE THREAD

**Issue by nunofilipesf** [airbnb/react-dates#721] opened 2017-09-22 14:34 UTC
If you set the cursor in a date field and press the 'tab' key, the cursor is moved to a link in the top of the page instead of the next input.
Works fine in Chrome.

Working sample in the storybook [(here)](http://airbnb.io/react-dates/?selectedKind=SingleDatePicker%20%28SDP%29&selectedStory=as%20part%20of%20a%20form&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel).

**Comment by gsferreira** [comment] 2017-09-22 14:45
Same issue here

**Comment by DiogoTx** [comment] 2017-09-22 14:49
Confirmed. 

Same behavior seen on Internet Explorer

**Comment by erin-doyle** [comment] 2017-10-25 02:29
The link that you are saying the cursor is going to is the Show Info button in the right corner of the Storybook and this is happening because that button has a tabIndex="0".  This gives it priority in the tab order and has nothing to do with the react-dates DatePicker functionality.  Unfortunately the Storybook does not provide the most accurate "environment" for testing tab order do to the other elements outside of the iframe that the DatePicker is rendered into.

**Comment by majapw** [comment] 2017-12-01 23:38
I think this is behaving as expected due to tab order. I can't repro any different behavior from Chrome in Firefox so I'm going to close this. :/

**Closed by majapw** 2017-12-01 23:38 UTC
