### ISSUE TITLE
Is moment required?

### ISSUE THREAD

**Issue by David-OConnor** [airbnb/react-dates#1889] opened 2019-12-29 03:11 UTC
Using version `21.5.1`. I'm having a hard time telling. I found several issues and a merged PR related to removing moment, but AFAIK from the docs and TS compiler messages I'm getting, the input and returned values are of type `moment.Moment`. What's the lowdown?

edit: I think it was [react-datepicker](https://github.com/Hacker0x01/react-datepicker) that excisised moment.

**Comment by ljharb** [comment] 2019-12-29 06:48
This package uses moment, and is likely to until Temporal is stage 3 and a polyfill/shim is thus viable in production. Moment is the defacto standard, and once Temporal arrives, nothing else will serve a purpose, so the churn in switching to any alternative (or supporting multiples) doesn't seem worth it in the interim.

Closing as a philosophical duplicate of #208.

**Closed by ljharb** 2019-12-29 06:48 UTC
