### ISSUE TITLE
Cursor jumping to the end of input upon typing

### ISSUE THREAD

**Issue by Norbo11** [airbnb/react-dates#1211] opened 2018-06-14 22:41 UTC
I have a pretty simple date picker. If I position my cursor in the middle of the date, and press backspace in order to change one character (for example, the month), the cursor jumps all the way to the end of the input field. This is very inconvenient for users, as I now have position my cursor again to the position I was trying to edit. This happens in your examples also. Is there a workaround to fix this?

**Comment by ggregoire** [comment] 2018-07-05 16:18
Duplicate of https://github.com/airbnb/react-dates/issues/1013

**Closed** 2018-07-05 16:21 UTC
