### ISSUE TITLE
Failed build :: Module not found

### ISSUE THREAD

**Issue by instant-coffee** [airbnb/react-dates#823] opened 2017-11-02 18:30 UTC
```
ERROR in ./constants.js
Module not found: Error: Can't resolve './lib/constants' in '/Users/lachlan/WebPro/react-dates'
 @ ./constants.js 2:17-43
 @ ./stories/DateRangePicker.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
```

Path in `constants.js` should be `module.exports = require('./src/constants');`

**Comment by ljharb** [comment] 2017-11-02 19:13
Duplicate of #818; now fixed in latest master.

**Closed by ljharb** 2017-11-02 19:13 UTC
