### ISSUE TITLE
Dates are changing automatically. (Looks like Artificial intelligence is incorporated)

### ISSUE THREAD

**Issue by naveenakadaba** [airbnb/react-dates#1807] opened 2019-09-27 07:14 UTC
**react-dates version**
e.g. react-dates@18.3.1

**Describe the bug**

**Source code (including props configuration)**
```
<DateRangePicker
  startDate={this.state.startDate}
  startDateId="your_unique_start_date_id"
  endDate={this.state.endDate}
  endDateId="your_unique_end_date_id"
  onDatesChange={({ startDate, endDate }) => this.setState({ startDate, endDate })}
  focusedInput={this.state.focusedInput}
  onFocusChange={focusedInput => this.setState({ focusedInput })}
/>
```
If you have custom methods that you are passing into a `react-dates` component, e.g. `onDatesChange`, `onFocusChange`, `renderMonth`, `isDayBlocked`, etc., please include the source for those as well.

**Screenshots/Gifs**
If applicable, add screenshots or gifs to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Is the issue reproducible in Storybook?**
Please link to the relevant storybook example

**Additional context**

**Comment by mmarkelov** [comment] 2019-09-27 07:16
Duplicate of #1804 #1800 #1799 #1795

**Comment by naveenakadaba** [comment] 2019-09-27 07:19
I know it's a duplicate. But it's not resolved yet. How this can happen? I had great opinion about Airbnb and their code have silly bugs like this?

**Closed** 2019-09-27 07:19 UTC

**Comment by naveenakadaba** [comment] 2019-09-27 07:20
Getting rid of react-dates, eslint-config-airbnb and other plugins. Thank you.

**Comment by ljharb** [comment] 2019-09-27 07:22
@naveenakadaba it is resolved, it's just not released yet.

If a single bug is enough to make you decide to jettison an entire ecosystem of code, then I'm not sure what to tell you. This is free software; you did not pay for it; you're not entitled to anything.

**Comment by naveenakadaba** [comment] 2019-09-27 07:31
Not a single bug. I have a list. I just pointed out a silly bug (Not expected from a organisation which has a great ecosystem of code). 

Anyway I appreciate your work. Its a good plugin though. Cheers
