### ISSUE TITLE
ESC key no longer closes picker

### ISSUE THREAD

**Issue by jeremyk** [airbnb/react-dates#457] opened 2017-04-18 21:30 UTC
I updated to 10.0.1 and it is broken. Reverting to 9.0.1 and it is fixed. Also verified that it doesn't work in the example here: http://airbnb.io/react-dates/

**Comment by majapw** [comment] 2017-05-03 16:56
I'm kind of surprised that escape ever closed the picker... because I never implemented that functionality. I'm going to say this is a dupe of https://github.com/airbnb/react-dates/issues/18 and close it in favor of that issue.

**Closed by majapw** 2017-05-03 16:56 UTC
Labels: bug

**Comment by jeremyk** [comment] 2017-05-03 17:17
Not sure it makes sense to close this as it is a regression. Andl you should probably take this out of your Keyboard shortcuts help:

> ESC Return to the date input field

**Comment by majapw** [comment] 2017-05-03 17:23
Wait, but that... does work? It doesn't close the datepicker, but focus certainly returns to the input (allowing you to type in a date and also tab over to the next input). Maybe the language is somewhat unclear?
![returning-focus-to-input](https://cloud.githubusercontent.com/assets/1383861/25672941/8158a5d2-2fea-11e7-9263-eb4792c07dcb.gif)

I still don't understand what behavior you were experiencing before that made this a regression (because again, I didn't think that hitting the escape key did anything before v10.0.0). Maybe if you shared a gif?

**Comment by jeremyk** [comment] 2017-05-03 17:29
Ok, I think the help text just wasn't clear to me as Esc was previously working differently for me. 

I guess the change to Esc might be specific to our implementation. I am happy to post a gif - is there a tool for creating that gif that you use?

**Comment by majapw** [comment] 2017-05-03 17:30
That would be super helpful @jeremyk! I generally use licecap for gif making. It's a pretty lightweight easy-to-use program.

**Comment by jeremyk** [comment] 2017-05-04 21:27
Here is a video of me clicking and hitting esc twice on the old version. I am pretty sure the reason it stopped working is that the new version grabs focus so that it can use keyboard events. So I am no longer getting the ESC key  (which I was using to blur the input which results in the picker closing). I wonder if you could add a keyDown callback so that I could make that work again? Or just an option to close it on ESC. Thanks!

![datepicker](https://cloud.githubusercontent.com/assets/223474/25725495/1ae67432-30d5-11e7-923f-525994003d31.gif)

**Comment by caub** [comment] 2021-04-20 08:02
```jsx
  const inputRef = useRef();
  useEffect(() => {
    const input = inputRef.current.container.querySelector('input');
    const closeOnEsc = e => {
      if (e.key === 'Escape' || e.key === 'Backspace') {
        setFocused(false);
      }
    }

    input.addEventListener('keydown', closeOnEsc);

    return () => input.removeEventListener('keydown', closeOnEsc);
  }, []);

  return (
    <SingleDatePicker
      ref={inputRef}
// ...
```
