### ISSUE TITLE
End Date: once you pick in date you cant change it with keyboard

### ISSUE THREAD

**Issue by kartikpunjabi** [airbnb/react-dates#361] opened 2017-03-08 00:17 UTC
End Date: once you pick in date you cant change it with keyboard

**Comment by majapw** [comment] 2017-03-17 20:30
I can't reproduce this on my machine. Here is a gif of me doing exactly that
![react-dates-end-date-typing](https://cloud.githubusercontent.com/assets/1383861/24061698/aea94e78-0b15-11e7-9cbd-1b06b1a0142c.gif)

I'm going to close this issue. If you find that this is still not working for you and you can provide more details as to the context, what device you are on, etc., then please feel free to reopen it with that information! (I'm trying to clean up our issues a little bit :P)

**Closed by majapw** 2017-03-17 20:30 UTC
