### ISSUE TITLE
Does it support changing year in the date picker?

### ISSUE THREAD

**Issue by wiz-kid** [airbnb/react-dates#1142] opened 2018-04-27 03:39 UTC
Does it provide support for changing year as well?
![image](https://user-images.githubusercontent.com/4576968/39343492-aa9e5754-49fa-11e8-92d5-369ce75e5bde.png)
&gt; for changing month
&gt;&gt; for changing year

**Comment by ljharb** [comment] 2018-04-27 03:42
Duplicate of #25

**Closed by ljharb** 2018-04-27 03:42 UTC
