### ISSUE TITLE
CalendarWeek: invalid value supplied to 0.,TypeError: `CalendarWeek` only accepts children of type withStyles(CalendarDay)

### ISSUE THREAD

**Issue by LeoIannacone** [airbnb/react-dates#1121] opened 2018-04-18 17:29 UTC
Hi,

I'm having issues with **16.6.1**:
```
  isToday = day => {
    return isSameDay(day, moment())
  }

  isHovered = day => {
    return isSameDay(day, this.state.hoverDate)
  }

  isSelected = day => {
    const value = this.props.getValue()
    return !_.isNil(value) && isSameDay(day, moment(value))
  }

  isBlocked = day => isBlocked(day, this.props)
.....

render() {
...
        <DayPickerSingleDateController
          numberOfMonths={1}
          initialVisibleMonth={this.getInitialMonth}
          navPrev={<IGreaterThan />}
          navNext={<IGreaterThan />}

          onDateChange={this.onChange}

          isOutsideRange={this.isBlocked}
          isDayBlocked={this.isBlocked}
          isDayHighlighted={this.isSelected}

          noBorder
        />
```

I'm getting:
```
Failed prop type: CalendarWeek: invalid value TypeError: CalendarWeek: invalid value supplied to 0.,TypeError: `CalendarWeek` only accepts children of type withStyles(CalendarDay),TypeError: `CalendarWeek` only accepts children of type withStyles(CustomizableCalendarDay) supplied to required children.
    in CalendarWeek (created by CalendarMonth)
    in CalendarMonth (created by withStyles(CalendarMonth))
    in withStyles(CalendarMonth) (created by CalendarMonthGrid)
    in div (created by CalendarMonthGrid)
    in div (created by CalendarMonthGrid)
    in CalendarMonthGrid (created by withStyles(CalendarMonthGrid))
    in withStyles(CalendarMonthGrid) (created by DayPicker)
    in div (created by DayPicker)
    in div (created by DayPicker)
    in div (created by DayPicker)
    in div (created by OutsideClickHandler)
    in OutsideClickHandler (created by DayPicker)
    in div (created by DayPicker)
    in DayPicker (created by withStyles(DayPicker))
    in withStyles(DayPicker) (created by DayPickerSingleDateController)
    in DayPickerSingleDateController (created by DateSelect)
    in div (created by DateSelect)
    in DateSelect (created by Formsy(DateSelect))
    in Formsy(DateSelect) (created by InvoiceAddCustomer)
    in form (created by Formsy)
    in Formsy (created by Form)
    in Form (created by InvoiceAddCustomer)
    in div (created by InvoiceAddCustomer)
    in div (created by InvoiceAddCustomer)
    in InvoiceAddCustomer (created by InvoiceEditorBase)
    in div (created by InvoiceEditorBase)
    in InvoiceEditorBase (created by InternalInvoiceEditor)
    in div (created by PanelOverlay)
    in div (created by PanelOverlay)
    in div (created by PanelOverlay)
    in div (created by ModalPortal)
    in div (created by ModalPortal)
    in ModalPortal (created by Modal)
    in Modal (created by PanelOverlay)
    in PanelOverlay (created by InternalInvoiceEditor)
    in div (created by Page)
    in Page (created by InternalInvoiceEditor)
    in InternalInvoiceEditor (created by withRouter(InternalInvoiceEditor))
    in withRouter(InternalInvoiceEditor) (created by RouterContext)
    in div (created by Job)
    in div (created by Job)
    in div (created by Job)
    in div (created by SplitView)
    in SplitView (created by Job)
    in div (created by Page)
    in Page (created by Job)
    in Job (created by RouterContext)
    in main (created by ProMain)
    in div (created by ProMain)
    in main (created by ProMain)
    in div (created by ProMain)
    in div (created by ProMain)
    in ProMain (created by withRouter(ProMain))
    in withRouter(ProMain) (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by ProRouter)
    in ProRouter (created by Router)
    in Router (created by Root)
    in Root
    in AppContainer
```

**Comment by majapw** [comment] 2018-04-18 18:28
Hi @LeoIannacone, I think this is a duplicate of https://github.com/airbnb/react-dates/issues/950. Are you also using `react-hot-loader`? I'm going to close this to move the convo over to that issue.

**Closed** 2018-04-18 18:28 UTC
Labels: duplicate

**Comment by slorber** [comment] 2019-05-13 12:35
@majapw I suggest you add this workaround as a comment in the other issues so that people know how to disable that warning until a proper fix is released in hot loader:

```
// @ts-ignore
import CalendarWeek from "react-dates/lib/components/CalendarWeek"
CalendarWeek && CalendarWeek.propTypes && delete CalendarWeek.propTypes['children'];
```

**Comment by ljharb** [comment] 2019-05-13 12:41
That’s not a good workaround to recommend; “ignore the warning” would be better.

**Comment by esetnik** [comment] 2019-05-15 19:21
Just wanted to chime in. I'm facing the same issue and also using `react-hot-loader`.
