### ISSUE TITLE
Start date changes value without user interaction

### ISSUE THREAD

**Issue by enricocasadei** [airbnb/react-dates#1804] opened 2019-09-26 15:56 UTC
**react-dates version**
react-dates@20.1.0 and @21.1.0

**Describe the bug**
startDate is switching to last day of the week when calendar is closed and open again.
Please check also in the storybook 
https://airbnb.io/react-dates/?path=/story/daterangepicker-drp--default

Check the first example in the storybook: click on the first date, select and then close the calendar. When clicked again the input change value to the last day of the week.

**Comment by mmarkelov** [comment] 2019-09-26 16:24
Duplicate of #1800 #1799 #1795

**Closed** 2019-09-26 16:27 UTC
