### ISSUE TITLE
The example doesn't work as is

### ISSUE THREAD

**Issue by mKurrels** [airbnb/react-dates#838] opened 2017-11-13 04:22 UTC
When I clone the application, run npm install then npm run storybook, I get this error:

```
ERROR in ./constants.js
Module not found: Error: Can't resolve './lib/constants' in '/Users/mike/workspace/react-dates'
 @ ./constants.js 2:17-43
 @ ./stories/DateRangePicker.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
```

There is no lib folder.

should ./constants.js read:
```
// eslint-disable-next-line import/no-unresolved
module.exports = require('./src/constants');
```

with the "lib" changed to "src"?

**Comment by majapw** [comment] 2017-11-13 04:49
I think we fixed this recently. Are you on the latest master?

**Comment by ljharb** [comment] 2017-11-13 04:58
Duplicate of #832, I think.

**Comment by majapw** [comment] 2017-11-14 06:07
@ljharb no, it's different and I thought we patched this in. Will fix now.

**Comment by majapw** [comment] 2017-11-14 06:10
Fixed in https://github.com/airbnb/react-dates/commit/55d6453642db3cc3d4a90a9dc32ee244bebbec15, please pull the latest master!

**Closed by majapw** 2017-11-14 06:10 UTC

**Comment by mKurrels** [comment] 2017-11-20 19:25
Thanks @majapw!
