### ISSUE TITLE
Is it possible to add year dropdown in date picker?

### ISSUE THREAD

**Issue by Subramanian8** [airbnb/react-dates#810] opened 2017-10-30 05:50 UTC
Is it possible to add year dropdown in date picker?

if possible means tell me how to do that?

for example see the given image.
![screenshot-2017-10-30 reactjs datepicker crafted by hackerone](https://user-images.githubusercontent.com/20462201/32156637-99218014-bd64-11e7-80fd-a70917a216b1.png)

After click the select dropdown button.
![screenshot-2017-10-30 reactjs datepicker crafted by hackerone2](https://user-images.githubusercontent.com/20462201/32156689-ec7c52a2-bd64-11e7-85cb-12b331900145.png)

**Comment by ljharb** [comment] 2017-10-30 16:09
Duplicate of #672.

**Closed by ljharb** 2017-10-30 16:09 UTC
