### ISSUE TITLE
Left/Right Arrow click improvements.

### ISSUE THREAD

**Issue by nsisodiya** [airbnb/react-dates#61] opened 2016-09-04 09:49 UTC
I noticed, When I click on Left and right Arrows,
1) It jump 2 month in default mode.
2) Sun-Mon.....Sat stay (kind of fixed)

====
when we click, it is better to jump only 1 month. which is better in IMO. again it is your choice.
Sun, Mon.... Sat is Fixed, when we click on Arrow, User expect them to move too.

**Comment by majapw** [comment] 2016-09-04 10:00
Sorry, is the datepicker jumping 2 months at a time for you? Can you show us a gif or video of the problem (and give us the deets of your system/browser)? 

As for number 2, the weekday headers stay fixed by design (def different from some other datepickers so maybe unexpected).

**Comment by nsisodiya** [comment] 2016-09-04 10:15
Sorry, I looked it closely , it is not jumping 2 month. I do not know but when I checked initially it gave me a `2 month jump` feeling.

Also, IMO - `weekday headers stay fixed by design` is not a good design since everything is moving then fixed header give strange feeling.

**Comment by majapw** [comment] 2016-09-16 00:41
This is something that we've landed on with our designers. We can review this in the future, but I don't see that changing any time soon as this was a design decision on our end.

**Closed by majapw** 2016-09-16 00:41 UTC
