### ISSUE TITLE
Selecting dates in DateRangePicker triggers a rerender

### ISSUE THREAD

**Issue by sergiubologa** [airbnb/react-dates#1565] opened 2019-03-03 13:34 UTC
**react-dates version**
react-dates@18.4.1 and above

**Describe the bug**
Starting from version `18.4.1`, when selecting a date the component is re-rendered and the user faces a flicker. This is more like an UX bug.

**Source code**
Here's a codesandbox with the code to reproduce the issue: https://codesandbox.io/s/9334257n7p

If I change the version to `18.4.0` everything works as expected.

**Screenshots/Gifs**
`18.4.1` or above:
![18 4 1](https://user-images.githubusercontent.com/10432669/53695851-698bc800-3dc9-11e9-8bdf-bd14522293ca.gif)

`18.4.0`
![18 4 0](https://user-images.githubusercontent.com/10432669/53695852-70b2d600-3dc9-11e9-8ed8-726c4989ecd5.gif)

**Desktop:**
 - OS: MAC OS, Windows
 - Browser Chrome
 - Version 72

**Is the issue reproducible in Storybook?**
This happens even in the live playground, on the default example: http://airbnb.io/react-dates

**Comment by sergiubologa** [comment] 2019-03-03 19:53
Seems like there's been only one change added to 18.4.1 and has been made in this PR: https://github.com/airbnb/react-dates/pull/1499.

@monokrome do you have any idea what may cause this?

**Comment by burtek** [comment] 2019-03-04 10:23
Isn't this a dup of #1523, fixed in 046c7f8d203dcdeaff54a8570316026ab7673125 ?

**Comment by burtek** [comment] 2019-03-04 10:43
Dup of #1523 ?

**Comment by ljharb** [comment] 2019-03-05 08:01
Closing as a duplicate of #1523.

**Closed by ljharb** 2019-03-05 08:01 UTC
