### ISSUE TITLE
Can not select start date before today

### ISSUE THREAD

**Issue by ggunia** [airbnb/react-dates#2013] opened 2020-06-23 07:38 UTC
**react-dates version**
react-dates@21.8.0

**Describe the bug**
Days before today are disabled

**Source code (including props configuration)**

```
<SingleDatePicker
    date={value ? moment(value) : null}
    onDateChange={(date) => handleValueChange(date.toDate())}
    focused={focused}
    placeholder="Select date"
    onFocusChange={({ focused }) => toggleFocused(focused)}
    id="StartDate"
    numberOfMonths={1}
    hideKeyboardShortcutsPanel
/>
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 

**Smartphone (please complete the following information):**
 - Version 83

**Is the issue reproducible in Storybook?**
http://airbnb.io/react-dates/?path=/story/singledatepicker-sdp--default

**Comment by mmarkelov** [comment] 2020-06-23 07:42
Duplicate of #1719, #1124, #1519, #1392, #1117, #1073, #985, #801, #718, #714, etc.
```js
isOutsideRange: () => false
```

**Closed** 2020-06-23 17:45 UTC
