### ISSUE TITLE
Don't allow blocked dates inside ranges

### ISSUE THREAD

**Issue by oldo** [airbnb/react-dates#296] opened 2017-02-05 11:09 UTC
First up, thank you so much for open sourcing and making this component available. Love your work!

I see that in the docs it is stated that:

> As of v1.0.0, we allow blocked dates inside of ranges.

Is there a flag that I can set to not allow blocked dates within a selected date range?

**Comment by majapw** [comment] 2017-02-07 23:54
Hi @oldo, unfortunately, due to some performance concerns in the implementation, this is not an option yet. I'm going to mark this issue as a dupe of https://github.com/airbnb/react-dates/issues/23. Def we need this so this will happen eventually, but has not yet been high priority. Pull Requests/Brainstorming/Ideas are definitely welcome.

**Closed by majapw** 2017-02-07 23:54 UTC
Labels: duplicate

**Comment by oldo** [comment] 2017-02-08 12:46
Thanks @majapw 
Not allowing blocked dates in a range is important for us so I'll be sure to share any developments that I make :-)

**Comment by JacobNicotra** [comment] 2021-12-13 01:04
any update this this?

**Comment by ljharb** [comment] 2021-12-13 02:13
@JacobNicotra no, because a) on any issue on github, if there's an update, it's posted _on the issue_, and b) because this is a duplicate of #23, so that is where an update would be posted.
