### ISSUE TITLE
SingleDatePicker shows wrong month name on locale change

### ISSUE THREAD

**Issue by sag1v** [airbnb/react-dates#637] opened 2017-07-24 10:29 UTC
Hi, i'm setting `moment.locale('he-IL');  \\ Hebrew`
The `DateRangePicker` shows the correct month and week-days correct, though the `SingleDatePicker ` shows only the week-days correct but the month name is still in english:

![singleday](https://user-images.githubusercontent.com/9153149/28519373-fbd3f4dc-7073-11e7-8918-4b9a2543c22e.png)
![rangeday](https://user-images.githubusercontent.com/9153149/28519376-01299d6a-7074-11e7-82f7-93810575eff4.png)

**Comment by majapw** [comment] 2017-07-24 16:15
Hi @sag1v, 

This is probably a duplicate of https://github.com/airbnb/react-dates/issues/480.

I think this has to do with when you set the moment locale. Probably what needs to happen is we need to check if the locale has changed in the `CalendarMonth` component and update the month name if that is the case. 

In the meantime, I think the patch is to use the `renderMonth` prop (`renderMonth={month => moment(month).format('YYYY MMMM')}`).

**Comment by sag1v** [comment] 2017-07-24 16:34
@majapw  thanks, i've tried it but no luck 😞

**Comment by majapw** [comment] 2017-07-24 16:49
Humm, can you share your code?

**Comment by mbinet** [comment] 2017-09-18 14:21
@sag1v I had the same issue, almost fixed it by setting the locale in the very first called component in my app, the one setting up redux and the router.
But almost, because the months are translated but not the placeholders "Start Date" and "End Date".

**Comment by majapw** [comment] 2017-09-18 16:48
Hi @mbinet, the placeholders aren't set with moment but instead are set manually as props. You'll have to pass a translated string into the DRP as `startDatePlaceholder` and `endDatePlaceholder`, I think! :)

**Closed** 2017-11-29 03:06 UTC
Labels: duplicate
