### ISSUE TITLE
Single date picker date change on focus

### ISSUE THREAD

**Issue by zedissime** [airbnb/react-dates#1799] opened 2019-09-24 07:14 UTC
When we focus the single date picker the date is changed without any action.

The issue is located on [the Storybook example ](https://airbnb.io/react-dates/?path=/story/singledatepicker-sdp--default)

![single_date_picker_issue](https://user-images.githubusercontent.com/1235591/65489527-9b6e9400-deab-11e9-882a-301bd2d59287.gif)

**Comment by mmarkelov** [comment] 2019-09-24 08:34
Duplicated #1795 
Fix is already merged, so it will be fine in new release

**Comment by TracyNgot** [comment] 2019-09-24 16:03
Thanks @mmarkelov! 
I also noticed this issue with the `dateRange` options. 

Can you tell us about the release version? 🙏

**Comment by ljharb** [comment] 2019-09-24 16:50
Closing as a duplicate of #1795.

**Closed by ljharb** 2019-09-24 16:50 UTC

**Comment by mmarkelov** [comment] 2019-09-24 17:16
Unfortunately I don’t know about release plans, @TracyNgot! You should ask core team member about it

**Comment by mmarkelov** [comment] 2019-09-25 12:47
@ljharb what do you think about releasing new version? I think this is critical bug and it may be a good idea to release it ASAP
