### ISSUE TITLE
Month navigation

### ISSUE THREAD

**Issue by Degee** [airbnb/react-dates#641] opened 2017-07-25 09:29 UTC
Hi there, i spend a lot of time on this and i need to find some solution or workaround.

We have a `SingleDatePicker` and we need to fetch data for actual viewed month . I though, that i can use `onClickNextMonth` or `onClickPrevMonth ` props -> on click to navigation fetch data, but there is no parameter in callbacks except event. Its also impossible to get actual viewed month right from `SingleDatePicker` component.

Then i was trying to change state of parent component and modify my property `viewedMonth` by + or - 1 month, but due to animation effect i had on multiclick on navigation not synchronous `viewedMonth` and actual viewed month of calendar.

Is there any solution, that we can on month change fetch data for actual month? In best case we need to show loader while we are fetching data, but this is another issue.

Thanks for helping!

**Comment by Degee** [comment] 2017-07-25 10:52
I found a quite clean solution, but still i would be glad for any answers to my previous questions.

Now i am replacing the calendar with loader, so this solves the problem with multiclick.

**Comment by adacosta** [comment] 2017-08-27 07:16
This sounds like a duplicate of https://github.com/airbnb/react-dates/pull/667 , which was recently resolved, merged, and released.

**Comment by ljharb** [comment] 2017-08-27 16:39
Part of this is handled by #667; part by #25.

**Closed by ljharb** 2017-08-27 16:39 UTC
