### ISSUE TITLE
SingleDatePicker should show the selected month when initialVisibleMonth changes

### ISSUE THREAD

**Issue by FezVrasta** [airbnb/react-dates#135] opened 2016-10-19 10:07 UTC
I'm creating a form with the city of departure, the one of arrival and the SingleDatePicker with all the available dates.

Most of the times the available dates will be in a different month of the one currently visible.
I can fix the problem with `initialVisibleMonth` for the first selection, but there's no way to move manually to the right month when the cities are changed and the `initialVisibleMonth` is changed.

**Comment by majapw** [comment] 2016-10-19 15:50
So I think this is a duplicate of https://github.com/airbnb/react-dates/issues/48 so I'm going to close this in favor of that discussion.

Right now, month is not a controlled property. To make this change, we'd need to do a lot of thinking about how the animation works, especially as it involves jumping more than one month at a time. Currently this is not on my roadmap and the `initialVisibleMonth` solves our present needs, but I am open to discussion on this and your thoughts.

**Closed by majapw** 2016-10-19 15:50 UTC
Labels: duplicate
