### ISSUE TITLE
Uncaught TypeError: Cannot read property 'contains' of null

### ISSUE THREAD

**Issue by jaynakus** [airbnb/react-dates#694] opened 2017-08-29 08:30 UTC
This happens when I click outside of the picker and it gets closed.

```
Uncaught TypeError: Cannot read property 'contains' of null
    at OutsideClickHandler.onOutsideClick (OutsideClickHandler.js:206)
    at eval (TargetEventHandlers.js:61)
    at Array.forEach (<anonymous>)
    at TargetEventHandlers.handleEvent (TargetEventHandlers.js:55)
```

Cannot track down why this error is popping out. What I could understand is that the method gets called several times and the last time it gets called this.childNode is null.

```
<SingleDatePicker
          date={item}
          onDateChange={this.handleChange}
          focused={this.state.focused}
          placeholder={placeholder}
          disabled={disabled || this.props.store.appStore.isBusy}
          onFocusChange={({focused}) => this.setState({focused})}
          showClearDate={showClearButton || false}
          isOutsideRange={this.checkRange}
        />
```

**Comment by mmakarin** [comment] 2017-08-29 12:17
Same error

**Comment by hfjallemark** [comment] 2017-08-29 16:32
I think this may be a duplicate of #437. Fixed but didn't make it into v12.5.0.. maintainers, any idea when the next release will be or how to work around this issue?

**Comment by majapw** [comment] 2017-08-29 17:04
v12.5.1. has been released! sorry for the delay. :)

**Closed** 2017-08-29 17:04 UTC

**Comment by hfjallemark** [comment] 2017-08-29 17:15
Awesome! Thanks @majapw.

**Comment by jaynakus** [comment] 2017-08-30 05:56
Thanks a lot it is fixed

**Comment by premji1528** [comment] 2020-04-10 14:37
This issue not occurring in the production environment. Also, In development mood when I update any code the view will refreshed in the browser in that only occurring if I refresh the page the issue will be gone...

**Comment by MuhammedMikayilov** [comment] 2020-09-07 08:44
I have same problem. But I cannot solve this
