### ISSUE TITLE
Overall layout of react-dates is a mess

### ISSUE THREAD

**Issue by angelosembrano** [airbnb/react-dates#115] opened 2016-10-12 06:34 UTC
When using `<DateRangePicker>`, this shows:

![1](https://cloud.githubusercontent.com/assets/22093912/19299757/d6aaf8e8-9088-11e6-8173-df46904fdbd9.PNG)
![2](https://cloud.githubusercontent.com/assets/22093912/19299756/d6a9722a-9088-11e6-9648-87fa10d8580f.PNG)
![3](https://cloud.githubusercontent.com/assets/22093912/19299758/d6b1e1ee-9088-11e6-9747-3070e4f89d09.PNG)

The Drag and Drop area (my component) as you can see was dragged to the bottom. And the sizes and layouts were disrupted!
Why is that? Were there errors in installing the package that resulted into this?

**Comment by ljharb** [comment] 2016-10-12 06:45
Are you using the included CSS? https://github.com/airbnb/react-dates#theming may help.

**Comment by majapw** [comment] 2016-10-12 15:19
Hi @angelosembrano, this is in fact caused by not including CSS. https://github.com/airbnb/react-dates/issues/45 also has some more information and we're working on adding that information to the README.

**Comment by majapw** [comment] 2016-10-13 18:47
Closing this because the solution is to load in the CSS. If you have information to add to the README on this process, please add a PR or your thoughts to #45

**Closed by majapw** 2016-10-13 18:47 UTC
