### ISSUE TITLE
Theming not working

### ISSUE THREAD

**Issue by ArunMichaelDsouza** [airbnb/react-dates#768] opened 2017-10-12 17:28 UTC
Hi, 

I am using ``react-dates v13.0.2`` with ``react v15.6.1``. I am trying to apply a custom theme to the ``DateRangePicker`` component. I am using the same example as shown on the project readme - 

```javascript
import ThemedStyleSheet from 'react-with-styles/lib/ThemedStyleSheet';
import DefaultTheme from 'react-dates/lib/theme/DefaultTheme';

ThemedStyleSheet.registerTheme({
  ...DefaultTheme,
  color: {
    ...DefaultTheme.color,
    highlighted: {
      backgroundColor: '#82E0AA',
      backgroundColor_active: '#58D68D',
      backgroundColor_hover: '#58D68D',
      color: '#186A3B',
      color_active: '#186A3B',
      color_hover: '#186A3B',
    },
  },
});
```

But I am getting this error - 

![screen shot 2017-10-12 at 10 50 29 pm](https://user-images.githubusercontent.com/4924614/31509836-794eb35a-afa0-11e7-9c62-bedbea433839.png)

**Comment by majapw** [comment] 2017-10-12 18:17
Hi @ArunMichaelDsouza, this is happening because you are not also registering an interface. This issue is a dupe of https://github.com/airbnb/react-dates/issues/758 and you can see some more conversation there. 

I will be following up with an update to the documentation to clarify things a bit.

**Closed** 2017-10-12 18:17 UTC
Labels: duplicate
