### ISSUE TITLE
Cannot clear dates after manually changing date by highlighting text

### ISSUE THREAD

**Issue by sarahdmsi** [airbnb/react-dates#805] opened 2017-10-26 20:49 UTC
When manually entering a date, if you use backspace it seems to work fine. However, if you highlight and type to replace text, it seems to get stuck where you can no longer clear it. See the linked screenshot for an example.

https://www.dropbox.com/s/50hv1vk7v8kyvxa/React%20Dates%20Highlight%20Issue.mov?dl=0

**Comment by majapw** [comment] 2017-10-27 17:52
O_o that's really weird, it looks like it's not committing the value for some reason (ie not clearing the `dateString` state) but that's weird because it's closing the datepicker... which I would assume would only happen when it properly committed things. D: Maybe something got lost when we exposed the real input. 

This def needs more investigation. I can dig around a bit but would appreciate any help. :)

**Comment by rakeshgunduka** [comment] 2017-10-29 19:38
This bug isn't reproducible. I tried the way it was done in the [screen shot example given](https://www.dropbox.com/s/50hv1vk7v8kyvxa/React%20Dates%20Highlight%20Issue.mov?dl=0) by @sarahdmsi but ended with no success.

**Closed** 2018-01-17 18:15 UTC
Labels: bug
