### ISSUE TITLE
SDP doesn't work on IE11

### ISSUE THREAD

**Issue by AsasinCree** [airbnb/react-dates#1614] opened 2019-04-10 09:55 UTC
**react-dates version**
react-dates@19.0.3

**Describe the bug**
When use SDP, open the calendar and click on a day but the chosen day won't fill on the date input.

**Screenshots/Gifs**
![image](https://user-images.githubusercontent.com/18276301/55869723-a8c3ea80-5bb9-11e9-84c3-810433a686b1.png)

**Desktop (please complete the following information):**
 - OS: win10 pro version 1809
 - Browser 
![image](https://user-images.githubusercontent.com/18276301/55869747-ba0cf700-5bb9-11e9-9273-3be7dbba5df4.png)

**Is the issue reproducible in Storybook?**
YES!!!!!!!!!!!!!!!!!!!!

**Additional context**

**Comment by AsasinCree** [comment] 2019-04-10 09:56
the unworked example in story book http://airbnb.io/react-dates/?selectedKind=SDP%20-%20Input%20Props&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

**Comment by AsasinCree** [comment] 2019-04-12 02:50
Duplicated with #1530 and fixed by PR #1578 . But no release so far, @ljharb Could it release as soon as possible?

**Comment by ljharb** [comment] 2019-04-12 03:18
Closed as a duplicate of #1530.

As soon as a maintainer has time, there will be a release.

**Closed by ljharb** 2019-04-12 03:18 UTC
Labels: bug, pull request wanted

**Comment by nikola-petrovic-vicert** [comment] 2019-04-12 13:59
We need this release as well @ljharb, @majapw

**Comment by i2chris** [comment] 2019-04-12 16:03
Is there an older version of react-dates that works with IE11 that I can use temporarily until a fix is released?

**Comment by AsasinCree** [comment] 2019-05-05 02:06
As almost one month pass, could you please help to trigger a release @ljharb, @majapw

**Comment by nikola-petrovic-vicert** [comment] 2019-05-07 11:29
hey guys, we really need this, can you give us release date at least or we have to switch to another library @ljharb, @majapw

**Comment by eiriks** [comment] 2019-05-20 14:35
Is the status on this issue that the bug fix exists, but is not published, and the suggested work-around five weeks later is to downgrade from 20.x to 18.4? That feels very wrong. @ljharb @majapw

**Comment by majapw** [comment] 2019-05-20 17:16
@eiriks I believe this should be addressed by #1530 in v20.2.0 

Please try it out!
