### ISSUE TITLE
isOutsideRange to handle disable dates if user clicked on endDate first

### ISSUE THREAD

**Issue by thian4** [airbnb/react-dates#1544] opened 2019-02-13 02:59 UTC
I've this requirement where I need to restrict the user to select only max 10 days, I used isOutsideRange and it worked.

```
isOutsideRange = day => {
    const { startDate, endDate } = this.state
    const todayDate = moment()

    // disable all dates before today
    if (!isInclusivelyAfterDay(day, startDate || todayDate)) {
      return true
    }

    // disable 10 days after startDate
    if (
      startDate &&
      !endDate &&
      isInclusivelyAfterDay(day, startDate.clone().add(10, 'days'))
    ) {
      return true
    }

    return false
  }
```

but if the user clicked on the endDate first, then above function need more handling. I'm ok to just make the endDate not clickable, but it seems that there's no option for that.

**Comment by ljharb** [comment] 2019-02-13 05:00
It seems like this is a duplicate of #1542 (your other issue) - I'm going to close it in favor of that one.

**Closed by ljharb** 2019-02-13 05:00 UTC
