### ISSUE TITLE
React DOM Unknown Prop Warning on implementation of onClose

### ISSUE THREAD

**Issue by hamisor** [airbnb/react-dates#444] opened 2017-04-13 03:39 UTC
The current implementation of onClose callback in DataInput.jsx uses onClose props in the input tag. This is not a recognised prop by react DOM or HTML DOM. Please change onClose to data-onClose to avoid react warning. 

Thanks

**Comment by haunguyen90** [comment] 2017-04-13 08:19
@ljharb Any ideas to fix it ?

**Comment by ljharb** [comment] 2017-04-13 09:36
Fix is incoming. Caused by #397.

**Closed** 2017-04-13 09:37 UTC
Labels: bug
