### ISSUE TITLE
Add  change Year functionality

### ISSUE THREAD

**Issue by sir-marc** [airbnb/react-dates#91] opened 2016-09-19 14:49 UTC
I never saw such a functionality.
Is it possible to implement this?
Otherwise you go crazy if you have to pick a date in 10 years.

**Comment by agupta93** [comment] 2016-09-19 15:10
#25 is an issue already addressing to the above request please check @sir-marc

**Comment by ljharb** [comment] 2016-09-19 15:29
Duplicate of #25.

**Closed by ljharb** 2016-09-19 15:29 UTC
Labels: feature request
