### ISSUE TITLE
DateRangePicker not rendering correctly (no css?)

### ISSUE THREAD

**Issue by RoarkeRandall** [airbnb/react-dates#109] opened 2016-10-06 18:32 UTC
Kind of hard to describe what is happening, I've uploaded a picture of what is happening: http://imgur.com/LmPetan the arrow fills the entire width of the window, no matter if it's in a smaller div. Also, not-styled calendars are always visible. 

This is on a practically empty react project (https://github.com/theverything/react-base)

It seems no css has been loaded. I installed by running the following:

`(
    export PKG=react-dates;
    npm info "$PKG" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g; s/ *//g' | xargs npm install --save "$PKG"
  )`

Any ideas?

**Comment by vladbalan** [comment] 2016-10-07 13:22
@RoarkeRandall This thread should help: #45

**Comment by RoarkeRandall** [comment] 2016-10-07 21:42
Hmm ok. Kind of hacky, but I copy pasted the datepicker css into a linked resource. The DateRangePicker now looks correct, but nothing happens when I click on the date inputs.

**Comment by vladbalan** [comment] 2016-10-08 06:20
I'm not sure what your setup is, but you could try importing the css file. `import 'react-dates/lib/css/_datepicker.css';` Or maybe adding this file (directly from `node_modules`) to the head of your html file. 

Regarding the date picker not doing anything, that's probably because you didn't set all the required properties for the component. Have you tried the example from the issue I linked to? 
```js
<SingleDatePicker
    id="date_input"
    date={date}
    focused={focused}
    onDateChange={this.onDateChange}
    onFocusChange={this.onFocusChange}
/>
```

**Comment by majapw** [comment] 2016-10-10 22:42
The CSS issue is a duplicate of https://github.com/airbnb/react-dates/issues/45 so I'm going to close this issue.

@vladbalan is probably right in guessing that you do not have your `onFocusChange` and `onDateChange` callbacks set up. If you look at https://github.com/airbnb/react-dates/tree/master/examples, you can see example wrappers for each of the SDP and the DRP. Let me know if that helps!

**Closed by majapw** 2016-10-10 22:42 UTC
Labels: duplicate

**Comment by vincerubinetti** [comment] 2018-12-16 22:40
Note that the css file is not a css module, so if you're using webpack, you'll have to set your css loader options to `modules: false` for `react-dates`. This took me a while to realize because I expected it to be a module like most libraries. Perhaps this should be said somewhere on the getting started/readme page.
