### ISSUE TITLE
Please Look on the warning message.

### ISSUE THREAD

**Issue by mathavan161293** [airbnb/react-dates#1850] opened 2019-10-29 11:16 UTC
backend.js:6 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: DateInput
r @ backend.js:6
printWarning @ react-dom.development.js:12466
lowPriorityWarningWithoutStack @ react-dom.development.js:12487
push../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:12654
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:25622
commitRootImpl @ react-dom.development.js:24849
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12259
commitRoot @ react-dom.development.js:24843
finishSyncRender @ react-dom.development.js:24220
performSyncWorkOnRoot @ react-dom.development.js:24194
(anonymous) @ react-dom.development.js:12313
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12259
flushSyncCallbackQueueImpl @ react-dom.development.js:12308
flushSyncCallbackQueue @ react-dom.development.js:12296
discreteUpdates$1 @ react-dom.development.js:24334
discreteUpdates @ react-dom.development.js:1485
dispatchDiscreteEvent @ react-dom.development.js:5949
backend.js:6 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: CalendarMonth, CalendarMonthGrid, DayPicker, DayPickerKeyboardShortcuts, DayPickerRangeController
r @ backend.js:6
printWarning @ react-dom.development.js:12466
lowPriorityWarningWithoutStack @ react-dom.development.js:12487
push../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:12654
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:25622
commitRootImpl @ react-dom.development.js:24849
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12259
commitRoot @ react-dom.development.js:24843
finishSyncRender @ react-dom.development.js:24220
performSyncWorkOnRoot @ react-dom.development.js:24194
(anonymous) @ react-dom.development.js:12313
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12259
flushSyncCallbackQueueImpl @ react-dom.development.js:12308
flushSyncCallbackQueue @ react-dom.development.js:12296
discreteUpdates$1 @ react-dom.development.js:24334
discreteUpdates @ react-dom.development.js:1485
dispatchDiscreteEvent @ react-dom.development.js:5949
backend.js:6 Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: DayPicker
![new_issues](https://user-images.githubusercontent.com/22838322/67762330-33433d00-fa6b-11e9-9b79-1f4cb7d43f07.PNG)

**Comment by ljharb** [comment] 2019-10-29 15:19
Duplicate of #1805. Duplicate of #1748.

**Closed by ljharb** 2019-10-29 15:19 UTC
