### ISSUE TITLE
The keyboard shortcuts panel toggle button is not displayed in Chrome

### ISSUE THREAD

**Issue by thiemeljiri** [airbnb/react-dates#1706] opened 2019-06-24 15:55 UTC
**react-dates version**
e.g. react-dates@20.1.0

**Describe the bug**
The keyboard shortcuts panel toggle button (right bottom corner triangle with question mark) is not displayed in Chrome. It is displayed in Firefox. It's completely missing in the DOM in Chrome and pressing the question mark also doesn't open the info panel.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 75.0.3770.100

**Is the issue reproducible in Storybook?**
Yes. In every story.

**Additional context**
I have hybrid notebook with touch screen and external display. If you try to detect something as if the device is touch or not this might be an important information. (And your solution not working correctly in that case.)
I suggest making the button appear only when focused and hide it visually in other cases. You should rather use approach similar to `sr-only-focusable` in Bootstrap 4. Hiding the button via any JS condition is not necessary and won't cover all the cases. It can be in the DOM all the time, like the skip links etc. This is a common and correct approach.

**Comment by erin-doyle** [comment] 2020-03-09 16:56
I believe this has been fixed, I'm not able to reproduce.  Can you please try updating to the latest version?  I'm going to close this but please reopen if it's still an issue.

**Closed by erin-doyle** 2020-03-09 16:56 UTC
