### ISSUE TITLE
DateController warning

### ISSUE THREAD

**Issue by niros-welldone** [airbnb/react-dates#1078] opened 2018-03-18 14:02 UTC
Hi i use react 16.0.0 and react-dates 16.3.6
While i using `DayPickerSingleDateController` or `DayPickerRangeController` with minimum require attributs i got that warning:

`Failed prop type: CalendarWeek: invalid value TypeError: CalendarWeek: invalid value supplied to 0.,TypeError: `CalendarWeek` only accepts children of type withStyles(CalendarDay),TypeError: `CalendarWeek` only accepts children of type withStyles(CustomizableCalendarDay) supplied to required children.`

Anyway the `SingleDatePicker` and `DateRangePicker` working fine.
any help :)

**Comment by johnkaza** [comment] 2018-03-21 21:36
+1

**Comment by EnriqueSalazar** [comment] 2018-03-23 12:44
Same as #1074

**Comment by ljharb** [comment] 2018-03-23 22:18
Closing as a duplicate of #950.

**Closed by ljharb** 2018-03-23 22:18 UTC

**Comment by omobosteven** [comment] 2018-04-01 11:42
I'm having the same error when I pick a date.

I'm using react 16.2.0 and react-dates 6.4.0

```
<SingleDatePicker
                  id="event-date"
                  date={this.state.date}
                  onDateChange={this.onDateChange}
                  focused={this.state.calenderFocused}
                  onFocusChange={this.onFocusChange}
                  numberOfMonths={1}
                  block={true}
                  displayFormat={'DD MMMM, YYYY'}
                />
```

`warning.js?da67:33 Warning: Failed prop type: CalendarWeek: invalid value TypeError: CalendarWeek: invalid value supplied to 0.,TypeError: `CalendarWeek` only accepts children of type withStyles(CalendarDay),TypeError: `CalendarWeek` only accepts children of type withStyles(CustomizableCalendarDay) supplied to required children.
    in CalendarWeek (created by CalendarMonth)
    in CalendarMonth (created by withStyles(CalendarMonth))
    in withStyles(CalendarMonth) (created by CalendarMonthGrid)
    in div (created by CalendarMonthGrid)
    in div (created by CalendarMonthGrid)
    in CalendarMonthGrid (created by withStyles(CalendarMonthGrid))
    in withStyles(CalendarMonthGrid) (created by DayPicker)
    in div (created by DayPicker)
    in div (created by DayPicker)
    in div (created by DayPicker)
    in div (created by OutsideClickHandler)
    in OutsideClickHandler (created by DayPicker)
    in div (created by DayPicker)
    in DayPicker (created by withStyles(DayPicker))
    in withStyles(DayPicker) (created by DayPickerSingleDateController)
    in DayPickerSingleDateController (created by SingleDatePicker)
    in div (created by SingleDatePicker)
    in div (created by OutsideClickHandler)
    in OutsideClickHandler (created by SingleDatePicker)
    in div (created by SingleDatePicker)
    in SingleDatePicker (created by withStyles(SingleDatePicker))
    in withStyles(SingleDatePicker) (created by AddEventPage)`
